// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct ClientAppInfo
	{
		public Int32 m_iPadding;
	};
	
	public enum EParentalFeature : int
	{
		k_EParentalFeatureInvalid = 0,
		k_EParentalFeatureStore = 1,
		k_EParentalFeatureCommunity = 2,
		k_EParentalFeatureProfile = 3,
		k_EParentalFeatureFriends = 4,
		k_EParentalFeatureNews = 5,
		k_EParentalFeatureTrading = 6,
		k_EParentalFeatureSettings = 7,
		k_EParentalFeatureConsole = 8,
		k_EParentalFeatureBrowser = 9,
		k_EParentalFeatureParentalSetup = 10,
		k_EParentalFeatureLibrary = 11,
		k_EParentalFeatureTest = 12,
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct COffline_OfflineLogonTicket
	{
		public Int32 m_iPadding;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class IClientUserVTable
	{
		public IntPtr GetHSteamUser0;
		public IntPtr LogOn1;
		public IntPtr LogOnWithPassword2;
		public IntPtr LogOnAndCreateNewSteamAccountIfNeeded3;
		public IntPtr LogOnConnectionless4;
		public IntPtr LogOff5;
		public IntPtr BLoggedOn6;
		public IntPtr GetLogonState7;
		public IntPtr BConnected8;
		public IntPtr BTryingToLogin9;
		public IntPtr GetSteamID10;
		public IntPtr GetConsoleSteamID11;
		public IntPtr IsVACBanned12;
		public IntPtr RequireShowVACBannedMessage13;
		public IntPtr AcknowledgeVACBanning14;
		public IntPtr SetEmail15;
		public IntPtr SetConfigString16;
		public IntPtr GetConfigString17;
		public IntPtr SetConfigInt18;
		public IntPtr GetConfigInt19;
		public IntPtr GetConfigStoreKeyName20;
		public IntPtr InitiateGameConnection21;
		public IntPtr InitiateGameConnectionOld22;
		public IntPtr TerminateGameConnection23;
		public IntPtr TerminateAppMultiStep24;
		public IntPtr SetSelfAsPrimaryChatDestination25;
		public IntPtr IsPrimaryChatDestination26;
		public IntPtr RequestLegacyCDKey27;
		public IntPtr AckGuestPass28;
		public IntPtr RedeemGuestPass29;
		public IntPtr GetGuestPassToGiveCount30;
		public IntPtr GetGuestPassToRedeemCount31;
		public IntPtr GetGuestPassToGiveInfo32;
		public IntPtr GetGuestPassToGiveOut33;
		public IntPtr GetGuestPassToRedeem34;
		public IntPtr GetGuestPassToRedeemInfo35;
		public IntPtr GetGuestPassToRedeemSenderName36;
		public IntPtr GetNumAppsInGuestPassesToRedeem37;
		public IntPtr GetAppsInGuestPassesToRedeem38;
		public IntPtr RequestStoreAuthURL39;
		public IntPtr SetLanguage40;
		public IntPtr TrackAppUsageEvent41;
		public IntPtr RaiseConnectionPriority42;
		public IntPtr ResetConnectionPriority43;
		public IntPtr BHasCachedCredentials44;
		public IntPtr SetAccountNameForCachedCredentialLogin45;
		public IntPtr GetCurrentWebAuthToken46;
		public IntPtr RequestWebAuthToken47;
		public IntPtr SetLoginInformation48;
		public IntPtr SetTwoFactorCode49;
		public IntPtr ClearAllLoginInformation50;
		public IntPtr GetLanguage51;
		public IntPtr BIsCyberCafe52;
		public IntPtr BIsAcademicAccount53;
		public IntPtr BIsPortal2EducationAccount54;
		public IntPtr BIsAlienwareDemoAccount55;
		public IntPtr CreateAccount56;
		public IntPtr ResetPassword57;
		public IntPtr ValidatePasswordResetCodeAndSendSms58;
		public IntPtr TrackNatTraversalStat59;
		public IntPtr TrackSteamUsageEvent60;
		public IntPtr TrackSteamGUIUsage61;
		public IntPtr SetComputerInUse62;
		public IntPtr BIsGameRunning63;
		public IntPtr BIsGameWindowReady64;
		public IntPtr BUpdateAppOwnershipTicket65;
		public IntPtr UpdateAppOwnershipTickets66;
		public IntPtr RequestCustomBinary67;
		public IntPtr GetCustomBinariesState68;
		public IntPtr RequestCustomBinaries69;
		public IntPtr SetCellID70;
		public IntPtr SetWinningPingTimeForCellID71;
		public IntPtr GetUserBaseFolder72;
		public IntPtr GetUserDataFolder73;
		public IntPtr GetUserConfigFolder74;
		public IntPtr GetAccountName75;
		public IntPtr GetAccountName76;
		public IntPtr IsPasswordRemembered77;
		public IntPtr RequiresLegacyCDKey78;
		public IntPtr GetLegacyCDKey79;
		public IntPtr SetLegacyCDKey80;
		public IntPtr WriteLegacyCDKey81;
		public IntPtr RemoveLegacyCDKey82;
		public IntPtr RequestLegacyCDKeyFromApp83;
		public IntPtr BIsAnyGameRunning84;
		public IntPtr TestAvailablePassword85;
		public IntPtr GetSteamGuardDetails86;
		public IntPtr GetTwoFactorDetails87;
		public IntPtr BHasTwoFactor88;
		public IntPtr RecoverAuthenticator89;
		public IntPtr ChangePassword90;
		public IntPtr GetEmail91;
		public IntPtr RequestForgottenPasswordEmail92;
		public IntPtr RequestAccountResetDetails93;
		public IntPtr FindAccountsByEmailAddress94;
		public IntPtr FindAccountsByCdKey95;
		public IntPtr GetNumAccountsWithEmailAddress96;
		public IntPtr IsAccountNameInUse97;
		public IntPtr Test_FakeConnectionTimeout98;
		public IntPtr RunInstallScript99;
		public IntPtr IsInstallScriptRunning100;
		public IntPtr GetInstallScriptState101;
		public IntPtr SpawnProcess102;
		public IntPtr GetAppOwnershipTicketLength103;
		public IntPtr GetAppOwnershipTicketData104;
		public IntPtr GetAppOwnershipTicketExtendedData105;
		public IntPtr GetMarketingMessageCount106;
		public IntPtr GetMarketingMessage107;
		public IntPtr GetAuthSessionTicket108;
		public IntPtr BeginAuthSession109;
		public IntPtr EndAuthSession110;
		public IntPtr CancelAuthTicket111;
		public IntPtr IsUserSubscribedAppInTicket112;
		public IntPtr AdvertiseGame113;
		public IntPtr RequestEncryptedAppTicket114;
		public IntPtr GetEncryptedAppTicket115;
		public IntPtr GetGameBadgeLevel116;
		public IntPtr GetPlayerSteamLevel117;
		public IntPtr SetAccountLimited118;
		public IntPtr BIsAccountLimited119;
		public IntPtr SetAccountCommunityBanned120;
		public IntPtr BIsAccountCommunityBanned121;
		public IntPtr SetLimitedAccountCanInviteFriends122;
		public IntPtr BLimitedAccountCanInviteFriends123;
		public IntPtr SendValidationEmail124;
		public IntPtr BGameConnectTokensAvailable125;
		public IntPtr NumGamesRunning126;
		public IntPtr GetRunningGameID127;
		public IntPtr GetRunningGamePID128;
		public IntPtr GetAccountSecurityPolicyFlags129;
		public IntPtr RequestPasswordChangeEmail130;
		public IntPtr ChangePasswordWithCode131;
		public IntPtr RequestEmailChange132;
		public IntPtr ChangeEmailWithCode133;
		public IntPtr SetClientStat134;
		public IntPtr VerifyPassword135;
		public IntPtr BSupportUser136;
		public IntPtr BNeedsSSANextSteamLogon137;
		public IntPtr ClearNeedsSSANextSteamLogon138;
		public IntPtr BIsAppOverlayEnabled139;
		public IntPtr BOverlayIgnoreChildProcesses140;
		public IntPtr BIsBehindNAT141;
		public IntPtr GetMicroTxnAppID142;
		public IntPtr GetMicroTxnOrderID143;
		public IntPtr BGetMicroTxnPrice144;
		public IntPtr GetMicroTxnLineItemCount145;
		public IntPtr BGetMicroTxnLineItem146;
		public IntPtr BIsSandboxMicroTxn147;
		public IntPtr BMicroTxnRequiresCachedPmtMethod148;
		public IntPtr AuthorizeMicroTxn149;
		public IntPtr BGetWalletBalance150;
		public IntPtr RequestMicroTxnInfo151;
		public IntPtr BMicroTxnRefundable152;
		public IntPtr BGetAppMinutesPlayed153;
		public IntPtr GetAppLastPlayedTime154;
		public IntPtr GetAppUpdateDisabledSecondsRemaining155;
		public IntPtr BGetGuideURL156;
		public IntPtr BPromptToVerifyEmail157;
		public IntPtr BPromptToChangePassword158;
		public IntPtr BAccountExtraSecurity159;
		public IntPtr BAccountShouldShowLockUI160;
		public IntPtr GetCountAuthedComputers161;
		public IntPtr BSteamGuardNewMachineNotification162;
		public IntPtr GetSteamGuardEnabledTime163;
		public IntPtr GetSteamGuardHistoryEntry164;
		public IntPtr SetSteamGuardNewMachineDialogResponse165;
		public IntPtr SetPhoneIsVerified166;
		public IntPtr BIsPhoneVerified167;
		public IntPtr SetPhoneIsIdentifying168;
		public IntPtr BIsPhoneIdentifying169;
		public IntPtr SetPhoneIsRequiringVerification170;
		public IntPtr BIsPhoneRequiringVerification171;
		public IntPtr ChangeTwoFactorAuthOptions172;
		public IntPtr Set2ndFactorAuthCode173;
		public IntPtr SetUserMachineName174;
		public IntPtr GetUserMachineName175;
		public IntPtr GetEmailDomainFromLogonFailure176;
		public IntPtr BIsSubscribedApp177;
		public IntPtr GetSubscribedApps178;
		public IntPtr RegisterActivationCode179;
		public IntPtr AckSystemIM180;
		public IntPtr RequestSpecialSurvey181;
		public IntPtr SendSpecialSurveyResponse182;
		public IntPtr RequestNotifications183;
		public IntPtr GetAppOwnershipInfo184;
		public IntPtr SendGameWebCallback185;
		public IntPtr StopStreaming186;
		public IntPtr BIsStreamingUIToRemoteDevice187;
		public IntPtr BIsCurrentlyNVStreaming188;
		public IntPtr RequestStopNVStreaming189;
		public IntPtr OnBigPictureStreamingResult190;
		public IntPtr OnBigPictureStreamingDone191;
		public IntPtr OnBigPictureStreamRestarting192;
		public IntPtr LockParentalLock193;
		public IntPtr UnlockParentalLock194;
		public IntPtr BIsParentalLockEnabled195;
		public IntPtr BIsParentalLockLocked196;
		public IntPtr BlockApp197;
		public IntPtr UnblockApp198;
		public IntPtr BIsAppBlocked199;
		public IntPtr BIsAppInBlockList200;
		public IntPtr BlockFeature201;
		public IntPtr UnblockFeature202;
		public IntPtr BIsFeatureBlocked203;
		public IntPtr BIsFeatureInBlockList204;
		public IntPtr GetParentalUnlockTime205;
		public IntPtr BGetRecoveryEmail206;
		public IntPtr RequestParentalRecoveryEmail207;
		public IntPtr BGetSerializedParentalSettings208;
		public IntPtr BSetParentalSettings209;
		public IntPtr BDisableParentalSettings210;
		public IntPtr BGetParentalWebToken211;
		public IntPtr BCanLogonOfflineMode212;
		public IntPtr LogOnOfflineMode213;
		public IntPtr ValidateOfflineLogonTicket214;
		public IntPtr BGetOfflineLogonTicket215;
		public IntPtr UploadLocalClientLogs216;
		public IntPtr SetAsyncNotificationEnabled217;
		public IntPtr BIsOtherSessionPlaying218;
		public IntPtr BKickOtherPlayingSession219;
		public IntPtr PerformAccountRecoveryUpload220;
		public IntPtr BIsAccountLockedDown221;
		private IntPtr DTorIClientUser222;
	};
	
	[InteropHelp.InterfaceVersion("CLIENTUSER_INTERFACE_VERSION001")]
	public class IClientUser : InteropHelp.NativeWrapper<IClientUserVTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetHSteamUser( IntPtr thisptr );
		public Int32 GetHSteamUser(  ) 
		{
			return this.GetFunction<NativeGetHSteamUser>( this.Functions.GetHSteamUser0 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLogOnBC( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bInteractive, UInt64 steamID );
		public void LogOn( bool bInteractive, CSteamID steamID ) 
		{
			this.GetFunction<NativeLogOnBC>( this.Functions.LogOn1 )( this.ObjectAddress, bInteractive, steamID.ConvertToUint64() ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLogOnWithPasswordBSS( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bInteractive, string pchLogin, string pchPassword );
		public void LogOnWithPassword( bool bInteractive, string pchLogin, string pchPassword ) 
		{
			this.GetFunction<NativeLogOnWithPasswordBSS>( this.Functions.LogOnWithPassword2 )( this.ObjectAddress, bInteractive, pchLogin, pchPassword ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLogOnAndCreateNewSteamAccountIfNeededB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bInteractive );
		public void LogOnAndCreateNewSteamAccountIfNeeded( bool bInteractive ) 
		{
			this.GetFunction<NativeLogOnAndCreateNewSteamAccountIfNeededB>( this.Functions.LogOnAndCreateNewSteamAccountIfNeeded3 )( this.ObjectAddress, bInteractive ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeLogOnConnectionless( IntPtr thisptr );
		public EResult LogOnConnectionless(  ) 
		{
			return this.GetFunction<NativeLogOnConnectionless>( this.Functions.LogOnConnectionless4 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLogOff( IntPtr thisptr );
		public void LogOff(  ) 
		{
			this.GetFunction<NativeLogOff>( this.Functions.LogOff5 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBLoggedOn( IntPtr thisptr );
		public bool BLoggedOn(  ) 
		{
			return this.GetFunction<NativeBLoggedOn>( this.Functions.BLoggedOn6 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate ELogonState NativeGetLogonState( IntPtr thisptr );
		public ELogonState GetLogonState(  ) 
		{
			return this.GetFunction<NativeGetLogonState>( this.Functions.GetLogonState7 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBConnected( IntPtr thisptr );
		public bool BConnected(  ) 
		{
			return this.GetFunction<NativeBConnected>( this.Functions.BConnected8 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBTryingToLogin( IntPtr thisptr );
		public bool BTryingToLogin(  ) 
		{
			return this.GetFunction<NativeBTryingToLogin>( this.Functions.BTryingToLogin9 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeGetSteamID( IntPtr thisptr, ref UInt64 retarg );
		public CSteamID GetSteamID(  ) 
		{
			UInt64 ret = 0; this.GetFunction<NativeGetSteamID>( this.Functions.GetSteamID10 )( this.ObjectAddress, ref ret ); return new CSteamID(ret);
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeGetConsoleSteamID( IntPtr thisptr, ref UInt64 retarg );
		public CSteamID GetConsoleSteamID(  ) 
		{
			UInt64 ret = 0; this.GetFunction<NativeGetConsoleSteamID>( this.Functions.GetConsoleSteamID11 )( this.ObjectAddress, ref ret ); return new CSteamID(ret);
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsVACBannedU( IntPtr thisptr, UInt32 nGameID );
		public bool IsVACBanned( UInt32 nGameID ) 
		{
			return this.GetFunction<NativeIsVACBannedU>( this.Functions.IsVACBanned12 )( this.ObjectAddress, nGameID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeRequireShowVACBannedMessageU( IntPtr thisptr, UInt32 nAppID );
		public bool RequireShowVACBannedMessage( UInt32 nAppID ) 
		{
			return this.GetFunction<NativeRequireShowVACBannedMessageU>( this.Functions.RequireShowVACBannedMessage13 )( this.ObjectAddress, nAppID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeAcknowledgeVACBanningU( IntPtr thisptr, UInt32 nAppID );
		public void AcknowledgeVACBanning( UInt32 nAppID ) 
		{
			this.GetFunction<NativeAcknowledgeVACBanningU>( this.Functions.AcknowledgeVACBanning14 )( this.ObjectAddress, nAppID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetEmailS( IntPtr thisptr, string pchEmail );
		public bool SetEmail( string pchEmail ) 
		{
			return this.GetFunction<NativeSetEmailS>( this.Functions.SetEmail15 )( this.ObjectAddress, pchEmail ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetConfigStringESS( IntPtr thisptr, ERegistrySubTree eRegistrySubTree, string pchKey, string pchValue );
		public bool SetConfigString( ERegistrySubTree eRegistrySubTree, string pchKey, string pchValue ) 
		{
			return this.GetFunction<NativeSetConfigStringESS>( this.Functions.SetConfigString16 )( this.ObjectAddress, eRegistrySubTree, pchKey, pchValue ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetConfigStringESSI( IntPtr thisptr, ERegistrySubTree eRegistrySubTree, string pchKey, StringBuilder pchValue, Int32 cbValue );
		public bool GetConfigString( ERegistrySubTree eRegistrySubTree, string pchKey, StringBuilder pchValue ) 
		{
			return this.GetFunction<NativeGetConfigStringESSI>( this.Functions.GetConfigString17 )( this.ObjectAddress, eRegistrySubTree, pchKey, pchValue, (Int32) pchValue.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetConfigIntESI( IntPtr thisptr, ERegistrySubTree eRegistrySubTree, string pchKey, Int32 iValue );
		public bool SetConfigInt( ERegistrySubTree eRegistrySubTree, string pchKey, Int32 iValue ) 
		{
			return this.GetFunction<NativeSetConfigIntESI>( this.Functions.SetConfigInt18 )( this.ObjectAddress, eRegistrySubTree, pchKey, iValue ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetConfigIntESI( IntPtr thisptr, ERegistrySubTree eRegistrySubTree, string pchKey, ref Int32 pValue );
		public bool GetConfigInt( ERegistrySubTree eRegistrySubTree, string pchKey, ref Int32 pValue ) 
		{
			return this.GetFunction<NativeGetConfigIntESI>( this.Functions.GetConfigInt19 )( this.ObjectAddress, eRegistrySubTree, pchKey, ref pValue ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetConfigStoreKeyNameESSI( IntPtr thisptr, ERegistrySubTree eRegistrySubTree, string pchKey, StringBuilder pchStoreName, Int32 cbStoreName );
		public bool GetConfigStoreKeyName( ERegistrySubTree eRegistrySubTree, string pchKey, StringBuilder pchStoreName ) 
		{
			return this.GetFunction<NativeGetConfigStoreKeyNameESSI>( this.Functions.GetConfigStoreKeyName20 )( this.ObjectAddress, eRegistrySubTree, pchKey, pchStoreName, (Int32) pchStoreName.Capacity ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeInitiateGameConnectionBICCUUB( IntPtr thisptr, Byte[] pOutputBlob, Int32 cbBlobMax, UInt64 steamIDGS, UInt64 gameID, UInt32 unIPServer, UInt16 usPortServer, [MarshalAs(UnmanagedType.I1)] bool bSecure );
		public Int32 InitiateGameConnection( Byte[] pOutputBlob, CSteamID steamIDGS, CGameID gameID, UInt32 unIPServer, UInt16 usPortServer, bool bSecure ) 
		{
			return this.GetFunction<NativeInitiateGameConnectionBICCUUB>( this.Functions.InitiateGameConnection21 )( this.ObjectAddress, pOutputBlob, (Int32) pOutputBlob.Length, steamIDGS.ConvertToUint64(), gameID.ConvertToUint64(), unIPServer, usPortServer, bSecure ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeInitiateGameConnectionOldBICCUUBBI( IntPtr thisptr, Byte[] pOutputBlob, Int32 cbBlobMax, UInt64 steamIDGS, UInt64 gameID, UInt32 unIPServer, UInt16 usPortServer, [MarshalAs(UnmanagedType.I1)] bool bSecure, Byte[] pvSteam2GetEncryptionKey, Int32 cbSteam2GetEncryptionKey );
		public Int32 InitiateGameConnectionOld( Byte[] pOutputBlob, CSteamID steamIDGS, CGameID gameID, UInt32 unIPServer, UInt16 usPortServer, bool bSecure, Byte[] pvSteam2GetEncryptionKey ) 
		{
			return this.GetFunction<NativeInitiateGameConnectionOldBICCUUBBI>( this.Functions.InitiateGameConnectionOld22 )( this.ObjectAddress, pOutputBlob, (Int32) pOutputBlob.Length, steamIDGS.ConvertToUint64(), gameID.ConvertToUint64(), unIPServer, usPortServer, bSecure, pvSteam2GetEncryptionKey, (Int32) pvSteam2GetEncryptionKey.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTerminateGameConnectionUU( IntPtr thisptr, UInt32 unIPServer, UInt16 usPortServer );
		public void TerminateGameConnection( UInt32 unIPServer, UInt16 usPortServer ) 
		{
			this.GetFunction<NativeTerminateGameConnectionUU>( this.Functions.TerminateGameConnection23 )( this.ObjectAddress, unIPServer, usPortServer ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeTerminateAppMultiStepUU( IntPtr thisptr, UInt32 arg0, UInt32 arg1 );
		public bool TerminateAppMultiStep( UInt32 arg0, UInt32 arg1 ) 
		{
			return this.GetFunction<NativeTerminateAppMultiStepUU>( this.Functions.TerminateAppMultiStep24 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetSelfAsPrimaryChatDestination( IntPtr thisptr );
		public void SetSelfAsPrimaryChatDestination(  ) 
		{
			this.GetFunction<NativeSetSelfAsPrimaryChatDestination>( this.Functions.SetSelfAsPrimaryChatDestination25 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsPrimaryChatDestination( IntPtr thisptr );
		public bool IsPrimaryChatDestination(  ) 
		{
			return this.GetFunction<NativeIsPrimaryChatDestination>( this.Functions.IsPrimaryChatDestination26 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestLegacyCDKeyU( IntPtr thisptr, UInt32 iAppID );
		public void RequestLegacyCDKey( UInt32 iAppID ) 
		{
			this.GetFunction<NativeRequestLegacyCDKeyU>( this.Functions.RequestLegacyCDKey27 )( this.ObjectAddress, iAppID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeAckGuestPassS( IntPtr thisptr, string pchGuestPassCode );
		public bool AckGuestPass( string pchGuestPassCode ) 
		{
			return this.GetFunction<NativeAckGuestPassS>( this.Functions.AckGuestPass28 )( this.ObjectAddress, pchGuestPassCode ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeRedeemGuestPassS( IntPtr thisptr, string pchGuestPassCode );
		public bool RedeemGuestPass( string pchGuestPassCode ) 
		{
			return this.GetFunction<NativeRedeemGuestPassS>( this.Functions.RedeemGuestPass29 )( this.ObjectAddress, pchGuestPassCode ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetGuestPassToGiveCount( IntPtr thisptr );
		public UInt32 GetGuestPassToGiveCount(  ) 
		{
			return this.GetFunction<NativeGetGuestPassToGiveCount>( this.Functions.GetGuestPassToGiveCount30 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetGuestPassToRedeemCount( IntPtr thisptr );
		public UInt32 GetGuestPassToRedeemCount(  ) 
		{
			return this.GetFunction<NativeGetGuestPassToRedeemCount>( this.Functions.GetGuestPassToRedeemCount31 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetGuestPassToGiveInfoUUUUUUUSI( IntPtr thisptr, UInt32 nPassIndex, ref UInt64 pgidGuestPassID, ref UInt32 pnPackageID, ref UInt32 pRTime32Created, ref UInt32 pRTime32Expiration, ref UInt32 pRTime32Sent, ref UInt32 pRTime32Redeemed, StringBuilder pchRecipientAddress, Int32 cRecipientAddressSize );
		public bool GetGuestPassToGiveInfo( UInt32 nPassIndex, ref UInt64 pgidGuestPassID, ref UInt32 pnPackageID, ref UInt32 pRTime32Created, ref UInt32 pRTime32Expiration, ref UInt32 pRTime32Sent, ref UInt32 pRTime32Redeemed, StringBuilder pchRecipientAddress ) 
		{
			return this.GetFunction<NativeGetGuestPassToGiveInfoUUUUUUUSI>( this.Functions.GetGuestPassToGiveInfo32 )( this.ObjectAddress, nPassIndex, ref pgidGuestPassID, ref pnPackageID, ref pRTime32Created, ref pRTime32Expiration, ref pRTime32Sent, ref pRTime32Redeemed, pchRecipientAddress, (Int32) pchRecipientAddress.Capacity ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetGuestPassToGiveOutU( IntPtr thisptr, UInt32 arg0 );
		public Int32 GetGuestPassToGiveOut( UInt32 arg0 ) 
		{
			return this.GetFunction<NativeGetGuestPassToGiveOutU>( this.Functions.GetGuestPassToGiveOut33 )( this.ObjectAddress, arg0 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetGuestPassToRedeemU( IntPtr thisptr, UInt32 arg0 );
		public Int32 GetGuestPassToRedeem( UInt32 arg0 ) 
		{
			return this.GetFunction<NativeGetGuestPassToRedeemU>( this.Functions.GetGuestPassToRedeem34 )( this.ObjectAddress, arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetGuestPassToRedeemInfoUUUUUUU( IntPtr thisptr, UInt32 nPassIndex, ref UInt64 pgidGuestPassID, ref UInt32 pnPackageID, ref UInt32 pRTime32Created, ref UInt32 pRTime32Expiration, ref UInt32 pRTime32Sent, ref UInt32 pRTime32Redeemed );
		public bool GetGuestPassToRedeemInfo( UInt32 nPassIndex, ref UInt64 pgidGuestPassID, ref UInt32 pnPackageID, ref UInt32 pRTime32Created, ref UInt32 pRTime32Expiration, ref UInt32 pRTime32Sent, ref UInt32 pRTime32Redeemed ) 
		{
			return this.GetFunction<NativeGetGuestPassToRedeemInfoUUUUUUU>( this.Functions.GetGuestPassToRedeemInfo35 )( this.ObjectAddress, nPassIndex, ref pgidGuestPassID, ref pnPackageID, ref pRTime32Created, ref pRTime32Expiration, ref pRTime32Sent, ref pRTime32Redeemed ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetGuestPassToRedeemSenderNameUSI( IntPtr thisptr, UInt32 nPassIndex, StringBuilder pchSenderName, Int32 cSenderNameSize );
		public bool GetGuestPassToRedeemSenderName( UInt32 nPassIndex, StringBuilder pchSenderName ) 
		{
			return this.GetFunction<NativeGetGuestPassToRedeemSenderNameUSI>( this.Functions.GetGuestPassToRedeemSenderName36 )( this.ObjectAddress, nPassIndex, pchSenderName, (Int32) pchSenderName.Capacity ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetNumAppsInGuestPassesToRedeem( IntPtr thisptr );
		public Int32 GetNumAppsInGuestPassesToRedeem(  ) 
		{
			return this.GetFunction<NativeGetNumAppsInGuestPassesToRedeem>( this.Functions.GetNumAppsInGuestPassesToRedeem37 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppsInGuestPassesToRedeemUU( IntPtr thisptr, ref UInt32 arg0, UInt32 arg1 );
		public Int32 GetAppsInGuestPassesToRedeem( ref UInt32 arg0, UInt32 arg1 ) 
		{
			return this.GetFunction<NativeGetAppsInGuestPassesToRedeemUU>( this.Functions.GetAppsInGuestPassesToRedeem38 )( this.ObjectAddress, ref arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRequestStoreAuthURLS( IntPtr thisptr, string arg0 );
		public UInt64 RequestStoreAuthURL( string arg0 ) 
		{
			return this.GetFunction<NativeRequestStoreAuthURLS>( this.Functions.RequestStoreAuthURL39 )( this.ObjectAddress, arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetLanguageS( IntPtr thisptr, string pchLanguage );
		public bool SetLanguage( string pchLanguage ) 
		{
			return this.GetFunction<NativeSetLanguageS>( this.Functions.SetLanguage40 )( this.ObjectAddress, pchLanguage ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTrackAppUsageEventCIS( IntPtr thisptr, UInt64 gameID, Int32 eAppUsageEvent, string pchExtraInfo );
		public void TrackAppUsageEvent( CGameID gameID, Int32 eAppUsageEvent, string pchExtraInfo ) 
		{
			this.GetFunction<NativeTrackAppUsageEventCIS>( this.Functions.TrackAppUsageEvent41 )( this.ObjectAddress, gameID.ConvertToUint64(), eAppUsageEvent, pchExtraInfo ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeRaiseConnectionPriorityE( IntPtr thisptr, EConnectionPriority eConnectionPriority );
		public Int32 RaiseConnectionPriority( EConnectionPriority eConnectionPriority ) 
		{
			return this.GetFunction<NativeRaiseConnectionPriorityE>( this.Functions.RaiseConnectionPriority42 )( this.ObjectAddress, eConnectionPriority ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeResetConnectionPriorityI( IntPtr thisptr, Int32 hRaiseConnectionPriorityPrev );
		public void ResetConnectionPriority( Int32 hRaiseConnectionPriorityPrev ) 
		{
			this.GetFunction<NativeResetConnectionPriorityI>( this.Functions.ResetConnectionPriority43 )( this.ObjectAddress, hRaiseConnectionPriorityPrev ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBHasCachedCredentialsS( IntPtr thisptr, string pchUnk );
		public bool BHasCachedCredentials( string pchUnk ) 
		{
			return this.GetFunction<NativeBHasCachedCredentialsS>( this.Functions.BHasCachedCredentials44 )( this.ObjectAddress, pchUnk ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetAccountNameForCachedCredentialLoginSB( IntPtr thisptr, string pchAccountName, [MarshalAs(UnmanagedType.I1)] bool bUnk );
		public bool SetAccountNameForCachedCredentialLogin( string pchAccountName, bool bUnk ) 
		{
			return this.GetFunction<NativeSetAccountNameForCachedCredentialLoginSB>( this.Functions.SetAccountNameForCachedCredentialLogin45 )( this.ObjectAddress, pchAccountName, bUnk ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetCurrentWebAuthTokenSISI( IntPtr thisptr, StringBuilder pchBuffer, Int32 cubBuffer, StringBuilder pchBuffer2, Int32 cubBuffer2 );
		public bool GetCurrentWebAuthToken( StringBuilder pchBuffer, StringBuilder pchBuffer2 ) 
		{
			return this.GetFunction<NativeGetCurrentWebAuthTokenSISI>( this.Functions.GetCurrentWebAuthToken46 )( this.ObjectAddress, pchBuffer, (Int32) pchBuffer.Capacity, pchBuffer2, (Int32) pchBuffer2.Capacity ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRequestWebAuthToken( IntPtr thisptr );
		public UInt64 RequestWebAuthToken(  ) 
		{
			return this.GetFunction<NativeRequestWebAuthToken>( this.Functions.RequestWebAuthToken47 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetLoginInformationSSB( IntPtr thisptr, string pchAccountName, string pchPassword, [MarshalAs(UnmanagedType.I1)] bool bRememberPassword );
		public void SetLoginInformation( string pchAccountName, string pchPassword, bool bRememberPassword ) 
		{
			this.GetFunction<NativeSetLoginInformationSSB>( this.Functions.SetLoginInformation48 )( this.ObjectAddress, pchAccountName, pchPassword, bRememberPassword ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetTwoFactorCodeS( IntPtr thisptr, string arg0 );
		public void SetTwoFactorCode( string arg0 ) 
		{
			this.GetFunction<NativeSetTwoFactorCodeS>( this.Functions.SetTwoFactorCode49 )( this.ObjectAddress, arg0 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeClearAllLoginInformation( IntPtr thisptr );
		public void ClearAllLoginInformation(  ) 
		{
			this.GetFunction<NativeClearAllLoginInformation>( this.Functions.ClearAllLoginInformation50 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetLanguageSI( IntPtr thisptr, StringBuilder pchLanguage, Int32 cbLanguage );
		public bool GetLanguage( StringBuilder pchLanguage ) 
		{
			return this.GetFunction<NativeGetLanguageSI>( this.Functions.GetLanguage51 )( this.ObjectAddress, pchLanguage, (Int32) pchLanguage.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsCyberCafe( IntPtr thisptr );
		public bool BIsCyberCafe(  ) 
		{
			return this.GetFunction<NativeBIsCyberCafe>( this.Functions.BIsCyberCafe52 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAcademicAccount( IntPtr thisptr );
		public bool BIsAcademicAccount(  ) 
		{
			return this.GetFunction<NativeBIsAcademicAccount>( this.Functions.BIsAcademicAccount53 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsPortal2EducationAccount( IntPtr thisptr );
		public bool BIsPortal2EducationAccount(  ) 
		{
			return this.GetFunction<NativeBIsPortal2EducationAccount>( this.Functions.BIsPortal2EducationAccount54 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAlienwareDemoAccount( IntPtr thisptr );
		public bool BIsAlienwareDemoAccount(  ) 
		{
			return this.GetFunction<NativeBIsAlienwareDemoAccount>( this.Functions.BIsAlienwareDemoAccount55 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeCreateAccountSSSISS( IntPtr thisptr, string pchAccountName, string pchNewPassword, string pchNewEmail, Int32 iQuestion, string pchNewQuestion, string pchNewAnswer );
		public void CreateAccount( string pchAccountName, string pchNewPassword, string pchNewEmail, Int32 iQuestion, string pchNewQuestion, string pchNewAnswer ) 
		{
			this.GetFunction<NativeCreateAccountSSSISS>( this.Functions.CreateAccount56 )( this.ObjectAddress, pchAccountName, pchNewPassword, pchNewEmail, iQuestion, pchNewQuestion, pchNewAnswer ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeResetPasswordSSSSS( IntPtr thisptr, string pchAccountName, string pchOldPassword, string pchNewPassword, string pchValidationCode, string pchAnswer );
		public UInt64 ResetPassword( string pchAccountName, string pchOldPassword, string pchNewPassword, string pchValidationCode, string pchAnswer ) 
		{
			return this.GetFunction<NativeResetPasswordSSSSS>( this.Functions.ResetPassword57 )( this.ObjectAddress, pchAccountName, pchOldPassword, pchNewPassword, pchValidationCode, pchAnswer ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeValidatePasswordResetCodeAndSendSmsSS( IntPtr thisptr, string arg0, string arg1 );
		public Int32 ValidatePasswordResetCodeAndSendSms( string arg0, string arg1 ) 
		{
			return this.GetFunction<NativeValidatePasswordResetCodeAndSendSmsSS>( this.Functions.ValidatePasswordResetCodeAndSendSms58 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTrackNatTraversalStatC( IntPtr thisptr, ref CNatTraversalStat pNatStat );
		public void TrackNatTraversalStat( ref CNatTraversalStat pNatStat ) 
		{
			this.GetFunction<NativeTrackNatTraversalStatC>( this.Functions.TrackNatTraversalStat59 )( this.ObjectAddress, ref pNatStat ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTrackSteamUsageEventEBU( IntPtr thisptr, ESteamUsageEvent eSteamUsageEvent, Byte[] pubKV, UInt32 cubKV );
		public void TrackSteamUsageEvent( ESteamUsageEvent eSteamUsageEvent, Byte[] pubKV ) 
		{
			this.GetFunction<NativeTrackSteamUsageEventEBU>( this.Functions.TrackSteamUsageEvent60 )( this.ObjectAddress, eSteamUsageEvent, pubKV, (UInt32) pubKV.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTrackSteamGUIUsageS( IntPtr thisptr, string arg0 );
		public void TrackSteamGUIUsage( string arg0 ) 
		{
			this.GetFunction<NativeTrackSteamGUIUsageS>( this.Functions.TrackSteamGUIUsage61 )( this.ObjectAddress, arg0 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetComputerInUse( IntPtr thisptr );
		public void SetComputerInUse(  ) 
		{
			this.GetFunction<NativeSetComputerInUse>( this.Functions.SetComputerInUse62 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsGameRunningC( IntPtr thisptr, UInt64 gameID );
		public bool BIsGameRunning( CGameID gameID ) 
		{
			return this.GetFunction<NativeBIsGameRunningC>( this.Functions.BIsGameRunning63 )( this.ObjectAddress, gameID.ConvertToUint64() ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsGameWindowReadyC( IntPtr thisptr, UInt64 gameID );
		public bool BIsGameWindowReady( CGameID gameID ) 
		{
			return this.GetFunction<NativeBIsGameWindowReadyC>( this.Functions.BIsGameWindowReady64 )( this.ObjectAddress, gameID.ConvertToUint64() ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBUpdateAppOwnershipTicketUBB( IntPtr thisptr, UInt32 nAppID, [MarshalAs(UnmanagedType.I1)] bool bOnlyUpdateIfStale, [MarshalAs(UnmanagedType.I1)] bool bIsDepot );
		public bool BUpdateAppOwnershipTicket( UInt32 nAppID, bool bOnlyUpdateIfStale, bool bIsDepot ) 
		{
			return this.GetFunction<NativeBUpdateAppOwnershipTicketUBB>( this.Functions.BUpdateAppOwnershipTicket65 )( this.ObjectAddress, nAppID, bOnlyUpdateIfStale, bIsDepot ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeUpdateAppOwnershipTicketsUUBB( IntPtr thisptr, ref UInt32 arg0, UInt32 arg1, [MarshalAs(UnmanagedType.I1)] bool arg2, [MarshalAs(UnmanagedType.I1)] bool arg3 );
		public Int32 UpdateAppOwnershipTickets( ref UInt32 arg0, UInt32 arg1, bool arg2, bool arg3 ) 
		{
			return this.GetFunction<NativeUpdateAppOwnershipTicketsUUBB>( this.Functions.UpdateAppOwnershipTickets66 )( this.ObjectAddress, ref arg0, arg1, arg2, arg3 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeRequestCustomBinarySUBB( IntPtr thisptr, string pszAbsolutePath, UInt32 nAppID, [MarshalAs(UnmanagedType.I1)] bool bForceUpdate, [MarshalAs(UnmanagedType.I1)] bool bAppLaunchRequest );
		public bool RequestCustomBinary( string pszAbsolutePath, UInt32 nAppID, bool bForceUpdate, bool bAppLaunchRequest ) 
		{
			return this.GetFunction<NativeRequestCustomBinarySUBB>( this.Functions.RequestCustomBinary67 )( this.ObjectAddress, pszAbsolutePath, nAppID, bForceUpdate, bAppLaunchRequest ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeGetCustomBinariesStateUU( IntPtr thisptr, UInt32 unAppID, ref UInt32 punProgress );
		public EResult GetCustomBinariesState( UInt32 unAppID, ref UInt32 punProgress ) 
		{
			return this.GetFunction<NativeGetCustomBinariesStateUU>( this.Functions.GetCustomBinariesState68 )( this.ObjectAddress, unAppID, ref punProgress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeRequestCustomBinariesUBBU( IntPtr thisptr, UInt32 unAppID, [MarshalAs(UnmanagedType.I1)] bool arg1, [MarshalAs(UnmanagedType.I1)] bool arg2, ref UInt32 arg3 );
		public EResult RequestCustomBinaries( UInt32 unAppID, bool arg1, bool arg2, ref UInt32 arg3 ) 
		{
			return this.GetFunction<NativeRequestCustomBinariesUBBU>( this.Functions.RequestCustomBinaries69 )( this.ObjectAddress, unAppID, arg1, arg2, ref arg3 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetCellIDU( IntPtr thisptr, UInt32 cellID );
		public void SetCellID( UInt32 cellID ) 
		{
			this.GetFunction<NativeSetCellIDU>( this.Functions.SetCellID70 )( this.ObjectAddress, cellID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetWinningPingTimeForCellIDU( IntPtr thisptr, UInt32 uPing );
		public void SetWinningPingTimeForCellID( UInt32 uPing ) 
		{
			this.GetFunction<NativeSetWinningPingTimeForCellIDU>( this.Functions.SetWinningPingTimeForCellID71 )( this.ObjectAddress, uPing ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate IntPtr NativeGetUserBaseFolder( IntPtr thisptr );
		public string GetUserBaseFolder(  ) 
		{
			return InteropHelp.DecodeANSIReturn( Marshal.PtrToStringAnsi( this.GetFunction<NativeGetUserBaseFolder>( this.Functions.GetUserBaseFolder72 )( this.ObjectAddress ) ) ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetUserDataFolderCSI( IntPtr thisptr, UInt64 gameID, StringBuilder pchBuffer, Int32 cubBuffer );
		public bool GetUserDataFolder( CGameID gameID, StringBuilder pchBuffer ) 
		{
			return this.GetFunction<NativeGetUserDataFolderCSI>( this.Functions.GetUserDataFolder73 )( this.ObjectAddress, gameID.ConvertToUint64(), pchBuffer, (Int32) pchBuffer.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetUserConfigFolderSI( IntPtr thisptr, StringBuilder pchBuffer, Int32 cubBuffer );
		public bool GetUserConfigFolder( StringBuilder pchBuffer ) 
		{
			return this.GetFunction<NativeGetUserConfigFolderSI>( this.Functions.GetUserConfigFolder74 )( this.ObjectAddress, pchBuffer, (Int32) pchBuffer.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetAccountNameSU( IntPtr thisptr, StringBuilder pchAccountName, UInt32 cb );
		public bool GetAccountName( StringBuilder pchAccountName ) 
		{
			return this.GetFunction<NativeGetAccountNameSU>( this.Functions.GetAccountName75 )( this.ObjectAddress, pchAccountName, (UInt32) pchAccountName.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetAccountNameCSU( IntPtr thisptr, UInt64 userID, StringBuilder pchAccountName, UInt32 cb );
		public bool GetAccountName( CSteamID userID, StringBuilder pchAccountName ) 
		{
			return this.GetFunction<NativeGetAccountNameCSU>( this.Functions.GetAccountName76 )( this.ObjectAddress, userID.ConvertToUint64(), pchAccountName, (UInt32) pchAccountName.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsPasswordRemembered( IntPtr thisptr );
		public bool IsPasswordRemembered(  ) 
		{
			return this.GetFunction<NativeIsPasswordRemembered>( this.Functions.IsPasswordRemembered77 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeRequiresLegacyCDKeyUB( IntPtr thisptr, UInt32 nAppID, ref bool pbUnk );
		public bool RequiresLegacyCDKey( UInt32 nAppID, ref bool pbUnk ) 
		{
			return this.GetFunction<NativeRequiresLegacyCDKeyUB>( this.Functions.RequiresLegacyCDKey78 )( this.ObjectAddress, nAppID, ref pbUnk ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetLegacyCDKeyUSI( IntPtr thisptr, UInt32 nAppID, StringBuilder pchKeyData, Int32 cbKeyData );
		public bool GetLegacyCDKey( UInt32 nAppID, StringBuilder pchKeyData ) 
		{
			return this.GetFunction<NativeGetLegacyCDKeyUSI>( this.Functions.GetLegacyCDKey79 )( this.ObjectAddress, nAppID, pchKeyData, (Int32) pchKeyData.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetLegacyCDKeyUS( IntPtr thisptr, UInt32 nAppID, string pchKeyData );
		public bool SetLegacyCDKey( UInt32 nAppID, string pchKeyData ) 
		{
			return this.GetFunction<NativeSetLegacyCDKeyUS>( this.Functions.SetLegacyCDKey80 )( this.ObjectAddress, nAppID, pchKeyData ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeWriteLegacyCDKeyU( IntPtr thisptr, UInt32 nAppID );
		public bool WriteLegacyCDKey( UInt32 nAppID ) 
		{
			return this.GetFunction<NativeWriteLegacyCDKeyU>( this.Functions.WriteLegacyCDKey81 )( this.ObjectAddress, nAppID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRemoveLegacyCDKeyU( IntPtr thisptr, UInt32 nAppID );
		public void RemoveLegacyCDKey( UInt32 nAppID ) 
		{
			this.GetFunction<NativeRemoveLegacyCDKeyU>( this.Functions.RemoveLegacyCDKey82 )( this.ObjectAddress, nAppID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestLegacyCDKeyFromAppUU( IntPtr thisptr, UInt32 nMainAppID, UInt32 nDLCAppID );
		public void RequestLegacyCDKeyFromApp( UInt32 nMainAppID, UInt32 nDLCAppID ) 
		{
			this.GetFunction<NativeRequestLegacyCDKeyFromAppUU>( this.Functions.RequestLegacyCDKeyFromApp83 )( this.ObjectAddress, nMainAppID, nDLCAppID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAnyGameRunning( IntPtr thisptr );
		public bool BIsAnyGameRunning(  ) 
		{
			return this.GetFunction<NativeBIsAnyGameRunning>( this.Functions.BIsAnyGameRunning84 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTestAvailablePasswordBI( IntPtr thisptr, Byte[] pubDigestPassword, Int32 cubDigestPassword );
		public void TestAvailablePassword( Byte[] pubDigestPassword ) 
		{
			this.GetFunction<NativeTestAvailablePasswordBI>( this.Functions.TestAvailablePassword85 )( this.ObjectAddress, pubDigestPassword, (Int32) pubDigestPassword.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeGetSteamGuardDetails( IntPtr thisptr );
		public void GetSteamGuardDetails(  ) 
		{
			this.GetFunction<NativeGetSteamGuardDetails>( this.Functions.GetSteamGuardDetails86 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetTwoFactorDetails( IntPtr thisptr );
		public Int32 GetTwoFactorDetails(  ) 
		{
			return this.GetFunction<NativeGetTwoFactorDetails>( this.Functions.GetTwoFactorDetails87 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBHasTwoFactor( IntPtr thisptr );
		public bool BHasTwoFactor(  ) 
		{
			return this.GetFunction<NativeBHasTwoFactor>( this.Functions.BHasTwoFactor88 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRecoverAuthenticatorSSSSS( IntPtr thisptr, string arg0, string arg1, string arg2, string arg3, string arg4 );
		public void RecoverAuthenticator( string arg0, string arg1, string arg2, string arg3, string arg4 ) 
		{
			this.GetFunction<NativeRecoverAuthenticatorSSSSS>( this.Functions.RecoverAuthenticator89 )( this.ObjectAddress, arg0, arg1, arg2, arg3, arg4 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeChangePasswordSS( IntPtr thisptr, string pchOldPassword, string pchNewPassword );
		public void ChangePassword( string pchOldPassword, string pchNewPassword ) 
		{
			this.GetFunction<NativeChangePasswordSS>( this.Functions.ChangePassword90 )( this.ObjectAddress, pchOldPassword, pchNewPassword ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetEmailSIB( IntPtr thisptr, StringBuilder pchEmail, Int32 cchEmail, ref bool pbValidated );
		public bool GetEmail( StringBuilder pchEmail, ref bool pbValidated ) 
		{
			return this.GetFunction<NativeGetEmailSIB>( this.Functions.GetEmail91 )( this.ObjectAddress, pchEmail, (Int32) pchEmail.Capacity, ref pbValidated ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestForgottenPasswordEmailSS( IntPtr thisptr, string pchAccountName, string pchTriedPassword );
		public void RequestForgottenPasswordEmail( string pchAccountName, string pchTriedPassword ) 
		{
			this.GetFunction<NativeRequestForgottenPasswordEmailSS>( this.Functions.RequestForgottenPasswordEmail92 )( this.ObjectAddress, pchAccountName, pchTriedPassword ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeRequestAccountResetDetailsSS( IntPtr thisptr, string arg0, string arg1 );
		public Int32 RequestAccountResetDetails( string arg0, string arg1 ) 
		{
			return this.GetFunction<NativeRequestAccountResetDetailsSS>( this.Functions.RequestAccountResetDetails93 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeFindAccountsByEmailAddressS( IntPtr thisptr, string pchEmailAddress );
		public void FindAccountsByEmailAddress( string pchEmailAddress ) 
		{
			this.GetFunction<NativeFindAccountsByEmailAddressS>( this.Functions.FindAccountsByEmailAddress94 )( this.ObjectAddress, pchEmailAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeFindAccountsByCdKeyS( IntPtr thisptr, string pchCdKey );
		public void FindAccountsByCdKey( string pchCdKey ) 
		{
			this.GetFunction<NativeFindAccountsByCdKeyS>( this.Functions.FindAccountsByCdKey95 )( this.ObjectAddress, pchCdKey ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeGetNumAccountsWithEmailAddressS( IntPtr thisptr, string pchEmailAddress );
		public void GetNumAccountsWithEmailAddress( string pchEmailAddress ) 
		{
			this.GetFunction<NativeGetNumAccountsWithEmailAddressS>( this.Functions.GetNumAccountsWithEmailAddress96 )( this.ObjectAddress, pchEmailAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeIsAccountNameInUseS( IntPtr thisptr, string pchAccountName );
		public void IsAccountNameInUse( string pchAccountName ) 
		{
			this.GetFunction<NativeIsAccountNameInUseS>( this.Functions.IsAccountNameInUse97 )( this.ObjectAddress, pchAccountName ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTest_FakeConnectionTimeout( IntPtr thisptr );
		public void Test_FakeConnectionTimeout(  ) 
		{
			this.GetFunction<NativeTest_FakeConnectionTimeout>( this.Functions.Test_FakeConnectionTimeout98 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeRunInstallScriptUISSB( IntPtr thisptr, ref UInt32 pAppIDs, Int32 cAppIDs, string pchInstallPath, string pchLanguage, [MarshalAs(UnmanagedType.I1)] bool bUninstall );
		public bool RunInstallScript( ref UInt32 pAppIDs, Int32 cAppIDs, string pchInstallPath, string pchLanguage, bool bUninstall ) 
		{
			return this.GetFunction<NativeRunInstallScriptUISSB>( this.Functions.RunInstallScript99 )( this.ObjectAddress, ref pAppIDs, cAppIDs, pchInstallPath, pchLanguage, bUninstall ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeIsInstallScriptRunning( IntPtr thisptr );
		public UInt32 IsInstallScriptRunning(  ) 
		{
			return this.GetFunction<NativeIsInstallScriptRunning>( this.Functions.IsInstallScriptRunning100 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetInstallScriptStateSUUU( IntPtr thisptr, StringBuilder pchDescription, UInt32 cchDescription, ref UInt32 punNumSteps, ref UInt32 punCurrStep );
		public bool GetInstallScriptState( StringBuilder pchDescription, ref UInt32 punNumSteps, ref UInt32 punCurrStep ) 
		{
			return this.GetFunction<NativeGetInstallScriptStateSUUU>( this.Functions.GetInstallScriptState101 )( this.ObjectAddress, pchDescription, (UInt32) pchDescription.Capacity, ref punNumSteps, ref punCurrStep ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSpawnProcessBUSSUSCUSU( IntPtr thisptr, Byte[] lpVACBlob, UInt32 cbBlobSize, string lpApplicationName, string lpCommandLine, UInt32 dwCreationFlags, string lpCurrentDirectory, UInt64 gameID, UInt32 nAppID, string pchGameName, UInt32 uUnk );
		public bool SpawnProcess( Byte[] lpVACBlob, string lpApplicationName, string lpCommandLine, UInt32 dwCreationFlags, string lpCurrentDirectory, CGameID gameID, UInt32 nAppID, string pchGameName, UInt32 uUnk ) 
		{
			return this.GetFunction<NativeSpawnProcessBUSSUSCUSU>( this.Functions.SpawnProcess102 )( this.ObjectAddress, lpVACBlob, (UInt32) lpVACBlob.Length, lpApplicationName, lpCommandLine, dwCreationFlags, lpCurrentDirectory, gameID.ConvertToUint64(), nAppID, pchGameName, uUnk ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAppOwnershipTicketLengthU( IntPtr thisptr, UInt32 nAppID );
		public UInt32 GetAppOwnershipTicketLength( UInt32 nAppID ) 
		{
			return this.GetFunction<NativeGetAppOwnershipTicketLengthU>( this.Functions.GetAppOwnershipTicketLength103 )( this.ObjectAddress, nAppID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAppOwnershipTicketDataUBU( IntPtr thisptr, UInt32 nAppID, Byte[] pvBuffer, UInt32 cbBufferLength );
		public UInt32 GetAppOwnershipTicketData( UInt32 nAppID, Byte[] pvBuffer ) 
		{
			return this.GetFunction<NativeGetAppOwnershipTicketDataUBU>( this.Functions.GetAppOwnershipTicketData104 )( this.ObjectAddress, nAppID, pvBuffer, (UInt32) pvBuffer.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAppOwnershipTicketExtendedDataUBUUUUU( IntPtr thisptr, UInt32 nAppID, Byte[] pvBuffer, UInt32 cbBufferLength, ref UInt32 piAppId, ref UInt32 piSteamId, ref UInt32 piSignature, ref UInt32 pcbSignature );
		public UInt32 GetAppOwnershipTicketExtendedData( UInt32 nAppID, Byte[] pvBuffer, ref UInt32 piAppId, ref UInt32 piSteamId, ref UInt32 piSignature, ref UInt32 pcbSignature ) 
		{
			return this.GetFunction<NativeGetAppOwnershipTicketExtendedDataUBUUUUU>( this.Functions.GetAppOwnershipTicketExtendedData105 )( this.ObjectAddress, nAppID, pvBuffer, (UInt32) pvBuffer.Length, ref piAppId, ref piSteamId, ref piSignature, ref pcbSignature ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetMarketingMessageCount( IntPtr thisptr );
		public Int32 GetMarketingMessageCount(  ) 
		{
			return this.GetFunction<NativeGetMarketingMessageCount>( this.Functions.GetMarketingMessageCount106 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetMarketingMessageIUSIE( IntPtr thisptr, Int32 cMarketingMessage, ref UInt64 gidMarketingMessageID, StringBuilder pubMsgUrl, Int32 cubMessageUrl, ref EMarketingMessageFlags eMarketingMssageFlags );
		public bool GetMarketingMessage( Int32 cMarketingMessage, ref UInt64 gidMarketingMessageID, StringBuilder pubMsgUrl, ref EMarketingMessageFlags eMarketingMssageFlags ) 
		{
			return this.GetFunction<NativeGetMarketingMessageIUSIE>( this.Functions.GetMarketingMessage107 )( this.ObjectAddress, cMarketingMessage, ref gidMarketingMessageID, pubMsgUrl, (Int32) pubMsgUrl.Capacity, ref eMarketingMssageFlags ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAuthSessionTicketBIU( IntPtr thisptr, Byte[] pMyAuthTicket, Int32 cbMaxMyAuthTicket, ref UInt32 pcbAuthTicket );
		public UInt32 GetAuthSessionTicket( Byte[] pMyAuthTicket, ref UInt32 pcbAuthTicket ) 
		{
			return this.GetFunction<NativeGetAuthSessionTicketBIU>( this.Functions.GetAuthSessionTicket108 )( this.ObjectAddress, pMyAuthTicket, (Int32) pMyAuthTicket.Length, ref pcbAuthTicket ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EBeginAuthSessionResult NativeBeginAuthSessionBIC( IntPtr thisptr, Byte[] pTheirAuthTicket, Int32 cbTicket, UInt64 steamID );
		public EBeginAuthSessionResult BeginAuthSession( Byte[] pTheirAuthTicket, CSteamID steamID ) 
		{
			return this.GetFunction<NativeBeginAuthSessionBIC>( this.Functions.BeginAuthSession109 )( this.ObjectAddress, pTheirAuthTicket, (Int32) pTheirAuthTicket.Length, steamID.ConvertToUint64() ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeEndAuthSessionC( IntPtr thisptr, UInt64 steamID );
		public void EndAuthSession( CSteamID steamID ) 
		{
			this.GetFunction<NativeEndAuthSessionC>( this.Functions.EndAuthSession110 )( this.ObjectAddress, steamID.ConvertToUint64() ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeCancelAuthTicketU( IntPtr thisptr, UInt32 hAuthTicket );
		public void CancelAuthTicket( UInt32 hAuthTicket ) 
		{
			this.GetFunction<NativeCancelAuthTicketU>( this.Functions.CancelAuthTicket111 )( this.ObjectAddress, hAuthTicket ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EUserHasLicenseForAppResult NativeIsUserSubscribedAppInTicketCU( IntPtr thisptr, UInt64 steamID, UInt32 appID );
		public EUserHasLicenseForAppResult IsUserSubscribedAppInTicket( CSteamID steamID, UInt32 appID ) 
		{
			return this.GetFunction<NativeIsUserSubscribedAppInTicketCU>( this.Functions.IsUserSubscribedAppInTicket112 )( this.ObjectAddress, steamID.ConvertToUint64(), appID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeAdvertiseGameCCUU( IntPtr thisptr, UInt64 gameID, UInt64 steamIDGameServer, UInt32 unIPServer, UInt16 usPortServer );
		public void AdvertiseGame( CGameID gameID, CSteamID steamIDGameServer, UInt32 unIPServer, UInt16 usPortServer ) 
		{
			this.GetFunction<NativeAdvertiseGameCCUU>( this.Functions.AdvertiseGame113 )( this.ObjectAddress, gameID.ConvertToUint64(), steamIDGameServer.ConvertToUint64(), unIPServer, usPortServer ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRequestEncryptedAppTicketBI( IntPtr thisptr, Byte[] pUserData, Int32 cbUserData );
		public UInt64 RequestEncryptedAppTicket( Byte[] pUserData ) 
		{
			return this.GetFunction<NativeRequestEncryptedAppTicketBI>( this.Functions.RequestEncryptedAppTicket114 )( this.ObjectAddress, pUserData, (Int32) pUserData.Length ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetEncryptedAppTicketBIU( IntPtr thisptr, Byte[] pTicket, Int32 cbMaxTicket, ref UInt32 pcbTicket );
		public bool GetEncryptedAppTicket( Byte[] pTicket, ref UInt32 pcbTicket ) 
		{
			return this.GetFunction<NativeGetEncryptedAppTicketBIU>( this.Functions.GetEncryptedAppTicket115 )( this.ObjectAddress, pTicket, (Int32) pTicket.Length, ref pcbTicket ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetGameBadgeLevelIB( IntPtr thisptr, Int32 nSeries, [MarshalAs(UnmanagedType.I1)] bool bFoil );
		public Int32 GetGameBadgeLevel( Int32 nSeries, bool bFoil ) 
		{
			return this.GetFunction<NativeGetGameBadgeLevelIB>( this.Functions.GetGameBadgeLevel116 )( this.ObjectAddress, nSeries, bFoil ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetPlayerSteamLevel( IntPtr thisptr );
		public Int32 GetPlayerSteamLevel(  ) 
		{
			return this.GetFunction<NativeGetPlayerSteamLevel>( this.Functions.GetPlayerSteamLevel117 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetAccountLimitedB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bAccountLimited );
		public void SetAccountLimited( bool bAccountLimited ) 
		{
			this.GetFunction<NativeSetAccountLimitedB>( this.Functions.SetAccountLimited118 )( this.ObjectAddress, bAccountLimited ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAccountLimited( IntPtr thisptr );
		public bool BIsAccountLimited(  ) 
		{
			return this.GetFunction<NativeBIsAccountLimited>( this.Functions.BIsAccountLimited119 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetAccountCommunityBannedB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bBanned );
		public void SetAccountCommunityBanned( bool bBanned ) 
		{
			this.GetFunction<NativeSetAccountCommunityBannedB>( this.Functions.SetAccountCommunityBanned120 )( this.ObjectAddress, bBanned ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAccountCommunityBanned( IntPtr thisptr );
		public bool BIsAccountCommunityBanned(  ) 
		{
			return this.GetFunction<NativeBIsAccountCommunityBanned>( this.Functions.BIsAccountCommunityBanned121 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetLimitedAccountCanInviteFriendsB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bCanInviteFriends );
		public void SetLimitedAccountCanInviteFriends( bool bCanInviteFriends ) 
		{
			this.GetFunction<NativeSetLimitedAccountCanInviteFriendsB>( this.Functions.SetLimitedAccountCanInviteFriends122 )( this.ObjectAddress, bCanInviteFriends ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBLimitedAccountCanInviteFriends( IntPtr thisptr );
		public bool BLimitedAccountCanInviteFriends(  ) 
		{
			return this.GetFunction<NativeBLimitedAccountCanInviteFriends>( this.Functions.BLimitedAccountCanInviteFriends123 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSendValidationEmail( IntPtr thisptr );
		public void SendValidationEmail(  ) 
		{
			this.GetFunction<NativeSendValidationEmail>( this.Functions.SendValidationEmail124 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGameConnectTokensAvailable( IntPtr thisptr );
		public bool BGameConnectTokensAvailable(  ) 
		{
			return this.GetFunction<NativeBGameConnectTokensAvailable>( this.Functions.BGameConnectTokensAvailable125 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeNumGamesRunning( IntPtr thisptr );
		public Int32 NumGamesRunning(  ) 
		{
			return this.GetFunction<NativeNumGamesRunning>( this.Functions.NumGamesRunning126 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeGetRunningGameIDI( IntPtr thisptr, ref UInt64 retarg, Int32 iGame );
		public CGameID GetRunningGameID( Int32 iGame ) 
		{
			UInt64 ret = 0; this.GetFunction<NativeGetRunningGameIDI>( this.Functions.GetRunningGameID127 )( this.ObjectAddress, ref ret, iGame ); return new CGameID(ret);
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetRunningGamePIDI( IntPtr thisptr, Int32 arg0 );
		public Int32 GetRunningGamePID( Int32 arg0 ) 
		{
			return this.GetFunction<NativeGetRunningGamePIDI>( this.Functions.GetRunningGamePID128 )( this.ObjectAddress, arg0 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAccountSecurityPolicyFlags( IntPtr thisptr );
		public UInt32 GetAccountSecurityPolicyFlags(  ) 
		{
			return this.GetFunction<NativeGetAccountSecurityPolicyFlags>( this.Functions.GetAccountSecurityPolicyFlags129 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestPasswordChangeEmailSI( IntPtr thisptr, string arg0, Int32 arg1 );
		public void RequestPasswordChangeEmail( string arg0, Int32 arg1 ) 
		{
			this.GetFunction<NativeRequestPasswordChangeEmailSI>( this.Functions.RequestPasswordChangeEmail130 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeChangePasswordWithCodeSSS( IntPtr thisptr, string pchOldPassword, string pchCode, string pchNewPassword );
		public void ChangePasswordWithCode( string pchOldPassword, string pchCode, string pchNewPassword ) 
		{
			this.GetFunction<NativeChangePasswordWithCodeSSS>( this.Functions.ChangePasswordWithCode131 )( this.ObjectAddress, pchOldPassword, pchCode, pchNewPassword ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestEmailChangeSS( IntPtr thisptr, string arg0, string arg1 );
		public void RequestEmailChange( string arg0, string arg1 ) 
		{
			this.GetFunction<NativeRequestEmailChangeSS>( this.Functions.RequestEmailChange132 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeChangeEmailWithCodeSSSSS( IntPtr thisptr, string arg0, string arg1, string arg2, string arg3, string arg4 );
		public void ChangeEmailWithCode( string arg0, string arg1, string arg2, string arg3, string arg4 ) 
		{
			this.GetFunction<NativeChangeEmailWithCodeSSSSS>( this.Functions.ChangeEmailWithCode133 )( this.ObjectAddress, arg0, arg1, arg2, arg3, arg4 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetClientStatEIUUU( IntPtr thisptr, EClientStat eStat, Int64 llValue, UInt32 nAppID, UInt32 nDepotID, UInt32 nCellID );
		public void SetClientStat( EClientStat eStat, Int64 llValue, UInt32 nAppID, UInt32 nDepotID, UInt32 nCellID ) 
		{
			this.GetFunction<NativeSetClientStatEIUUU>( this.Functions.SetClientStat134 )( this.ObjectAddress, eStat, llValue, nAppID, nDepotID, nCellID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeVerifyPasswordS( IntPtr thisptr, string pchPassword );
		public void VerifyPassword( string pchPassword ) 
		{
			this.GetFunction<NativeVerifyPasswordS>( this.Functions.VerifyPassword135 )( this.ObjectAddress, pchPassword ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBSupportUser( IntPtr thisptr );
		public bool BSupportUser(  ) 
		{
			return this.GetFunction<NativeBSupportUser>( this.Functions.BSupportUser136 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBNeedsSSANextSteamLogon( IntPtr thisptr );
		public bool BNeedsSSANextSteamLogon(  ) 
		{
			return this.GetFunction<NativeBNeedsSSANextSteamLogon>( this.Functions.BNeedsSSANextSteamLogon137 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeClearNeedsSSANextSteamLogon( IntPtr thisptr );
		public void ClearNeedsSSANextSteamLogon(  ) 
		{
			this.GetFunction<NativeClearNeedsSSANextSteamLogon>( this.Functions.ClearNeedsSSANextSteamLogon138 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAppOverlayEnabledC( IntPtr thisptr, UInt64 gameID );
		public bool BIsAppOverlayEnabled( CGameID gameID ) 
		{
			return this.GetFunction<NativeBIsAppOverlayEnabledC>( this.Functions.BIsAppOverlayEnabled139 )( this.ObjectAddress, gameID.ConvertToUint64() ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBOverlayIgnoreChildProcessesC( IntPtr thisptr, UInt64 arg0 );
		public bool BOverlayIgnoreChildProcesses( CGameID arg0 ) 
		{
			return this.GetFunction<NativeBOverlayIgnoreChildProcessesC>( this.Functions.BOverlayIgnoreChildProcesses140 )( this.ObjectAddress, arg0.ConvertToUint64() ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsBehindNAT( IntPtr thisptr );
		public bool BIsBehindNAT(  ) 
		{
			return this.GetFunction<NativeBIsBehindNAT>( this.Functions.BIsBehindNAT141 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetMicroTxnAppIDU( IntPtr thisptr, UInt64 gidTransID );
		public UInt32 GetMicroTxnAppID( UInt64 gidTransID ) 
		{
			return this.GetFunction<NativeGetMicroTxnAppIDU>( this.Functions.GetMicroTxnAppID142 )( this.ObjectAddress, gidTransID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeGetMicroTxnOrderIDU( IntPtr thisptr, UInt64 gidTransID );
		public UInt64 GetMicroTxnOrderID( UInt64 gidTransID ) 
		{
			return this.GetFunction<NativeGetMicroTxnOrderIDU>( this.Functions.GetMicroTxnOrderID143 )( this.ObjectAddress, gidTransID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetMicroTxnPriceUCCBC( IntPtr thisptr, UInt64 gidTransID, ref CAmount pamtTotal, ref CAmount pamtTax, ref bool pbVat, ref CAmount pUnk );
		public bool BGetMicroTxnPrice( UInt64 gidTransID, ref CAmount pamtTotal, ref CAmount pamtTax, ref bool pbVat, ref CAmount pUnk ) 
		{
			return this.GetFunction<NativeBGetMicroTxnPriceUCCBC>( this.Functions.BGetMicroTxnPrice144 )( this.ObjectAddress, gidTransID, ref pamtTotal, ref pamtTax, ref pbVat, ref pUnk ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetMicroTxnLineItemCountU( IntPtr thisptr, UInt64 gidTransID );
		public Int32 GetMicroTxnLineItemCount( UInt64 gidTransID ) 
		{
			return this.GetFunction<NativeGetMicroTxnLineItemCountU>( this.Functions.GetMicroTxnLineItemCount145 )( this.ObjectAddress, gidTransID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetMicroTxnLineItemUUCUSUIBCB( IntPtr thisptr, UInt64 gidTransID, UInt32 unLineItem, ref CAmount pamt, ref UInt32 punQuantity, StringBuilder pchDescription, UInt32 cubDescriptionLength, ref Int32 pRecurringTimeUnit, Byte[] pRecurringFrequency, ref CAmount pRecurringAmount, ref bool pbUnk );
		public bool BGetMicroTxnLineItem( UInt64 gidTransID, UInt32 unLineItem, ref CAmount pamt, ref UInt32 punQuantity, StringBuilder pchDescription, ref Int32 pRecurringTimeUnit, Byte[] pRecurringFrequency, ref CAmount pRecurringAmount, ref bool pbUnk ) 
		{
			return this.GetFunction<NativeBGetMicroTxnLineItemUUCUSUIBCB>( this.Functions.BGetMicroTxnLineItem146 )( this.ObjectAddress, gidTransID, unLineItem, ref pamt, ref punQuantity, pchDescription, (UInt32) pchDescription.Capacity, ref pRecurringTimeUnit, pRecurringFrequency, ref pRecurringAmount, ref pbUnk ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsSandboxMicroTxnUB( IntPtr thisptr, UInt64 gidTransID, ref bool pbSandbox );
		public bool BIsSandboxMicroTxn( UInt64 gidTransID, ref bool pbSandbox ) 
		{
			return this.GetFunction<NativeBIsSandboxMicroTxnUB>( this.Functions.BIsSandboxMicroTxn147 )( this.ObjectAddress, gidTransID, ref pbSandbox ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBMicroTxnRequiresCachedPmtMethodUB( IntPtr thisptr, UInt64 gidTransID, ref bool pbRequired );
		public bool BMicroTxnRequiresCachedPmtMethod( UInt64 gidTransID, ref bool pbRequired ) 
		{
			return this.GetFunction<NativeBMicroTxnRequiresCachedPmtMethodUB>( this.Functions.BMicroTxnRequiresCachedPmtMethod148 )( this.ObjectAddress, gidTransID, ref pbRequired ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeAuthorizeMicroTxnUE( IntPtr thisptr, UInt64 gidTransID, EMicroTxnAuthResponse eMicroTxnAuthResponse );
		public UInt64 AuthorizeMicroTxn( UInt64 gidTransID, EMicroTxnAuthResponse eMicroTxnAuthResponse ) 
		{
			return this.GetFunction<NativeAuthorizeMicroTxnUE>( this.Functions.AuthorizeMicroTxn149 )( this.ObjectAddress, gidTransID, eMicroTxnAuthResponse ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetWalletBalanceBCC( IntPtr thisptr, ref bool pbHasWallet, ref CAmount pamtBalance, ref CAmount arg2 );
		public bool BGetWalletBalance( ref bool pbHasWallet, ref CAmount pamtBalance, ref CAmount arg2 ) 
		{
			return this.GetFunction<NativeBGetWalletBalanceBCC>( this.Functions.BGetWalletBalance150 )( this.ObjectAddress, ref pbHasWallet, ref pamtBalance, ref arg2 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRequestMicroTxnInfoU( IntPtr thisptr, UInt64 gidTransID );
		public UInt64 RequestMicroTxnInfo( UInt64 gidTransID ) 
		{
			return this.GetFunction<NativeRequestMicroTxnInfoU>( this.Functions.RequestMicroTxnInfo151 )( this.ObjectAddress, gidTransID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBMicroTxnRefundableU( IntPtr thisptr, UInt64 gidTransID );
		public bool BMicroTxnRefundable( UInt64 gidTransID ) 
		{
			return this.GetFunction<NativeBMicroTxnRefundableU>( this.Functions.BMicroTxnRefundable152 )( this.ObjectAddress, gidTransID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetAppMinutesPlayedUII( IntPtr thisptr, UInt32 nAppId, ref Int32 pnForever, ref Int32 pnLastTwoWeeks );
		public bool BGetAppMinutesPlayed( UInt32 nAppId, ref Int32 pnForever, ref Int32 pnLastTwoWeeks ) 
		{
			return this.GetFunction<NativeBGetAppMinutesPlayedUII>( this.Functions.BGetAppMinutesPlayed153 )( this.ObjectAddress, nAppId, ref pnForever, ref pnLastTwoWeeks ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAppLastPlayedTimeU( IntPtr thisptr, UInt32 nAppId );
		public UInt32 GetAppLastPlayedTime( UInt32 nAppId ) 
		{
			return this.GetFunction<NativeGetAppLastPlayedTimeU>( this.Functions.GetAppLastPlayedTime154 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppUpdateDisabledSecondsRemainingU( IntPtr thisptr, UInt32 arg0 );
		public Int32 GetAppUpdateDisabledSecondsRemaining( UInt32 arg0 ) 
		{
			return this.GetFunction<NativeGetAppUpdateDisabledSecondsRemainingU>( this.Functions.GetAppUpdateDisabledSecondsRemaining155 )( this.ObjectAddress, arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetGuideURLUSU( IntPtr thisptr, UInt32 uAppID, StringBuilder pchURL, UInt32 cchURL );
		public bool BGetGuideURL( UInt32 uAppID, StringBuilder pchURL ) 
		{
			return this.GetFunction<NativeBGetGuideURLUSU>( this.Functions.BGetGuideURL156 )( this.ObjectAddress, uAppID, pchURL, (UInt32) pchURL.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBPromptToVerifyEmail( IntPtr thisptr );
		public bool BPromptToVerifyEmail(  ) 
		{
			return this.GetFunction<NativeBPromptToVerifyEmail>( this.Functions.BPromptToVerifyEmail157 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBPromptToChangePassword( IntPtr thisptr );
		public bool BPromptToChangePassword(  ) 
		{
			return this.GetFunction<NativeBPromptToChangePassword>( this.Functions.BPromptToChangePassword158 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBAccountExtraSecurity( IntPtr thisptr );
		public bool BAccountExtraSecurity(  ) 
		{
			return this.GetFunction<NativeBAccountExtraSecurity>( this.Functions.BAccountExtraSecurity159 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBAccountShouldShowLockUI( IntPtr thisptr );
		public bool BAccountShouldShowLockUI(  ) 
		{
			return this.GetFunction<NativeBAccountShouldShowLockUI>( this.Functions.BAccountShouldShowLockUI160 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCountAuthedComputers( IntPtr thisptr );
		public Int32 GetCountAuthedComputers(  ) 
		{
			return this.GetFunction<NativeGetCountAuthedComputers>( this.Functions.GetCountAuthedComputers161 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBSteamGuardNewMachineNotification( IntPtr thisptr );
		public bool BSteamGuardNewMachineNotification(  ) 
		{
			return this.GetFunction<NativeBSteamGuardNewMachineNotification>( this.Functions.BSteamGuardNewMachineNotification162 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetSteamGuardEnabledTime( IntPtr thisptr );
		public UInt32 GetSteamGuardEnabledTime(  ) 
		{
			return this.GetFunction<NativeGetSteamGuardEnabledTime>( this.Functions.GetSteamGuardEnabledTime163 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetSteamGuardHistoryEntryIUUBSISI( IntPtr thisptr, Int32 iEntryIndex, ref UInt32 puTimestamp, ref UInt32 puIP, ref bool pbIsRemembered, StringBuilder pchGeolocInfo, Int32 cchGeolocInfo, StringBuilder pchUnk, Int32 cbUnk );
		public bool GetSteamGuardHistoryEntry( Int32 iEntryIndex, ref UInt32 puTimestamp, ref UInt32 puIP, ref bool pbIsRemembered, StringBuilder pchGeolocInfo, StringBuilder pchUnk ) 
		{
			return this.GetFunction<NativeGetSteamGuardHistoryEntryIUUBSISI>( this.Functions.GetSteamGuardHistoryEntry164 )( this.ObjectAddress, iEntryIndex, ref puTimestamp, ref puIP, ref pbIsRemembered, pchGeolocInfo, (Int32) pchGeolocInfo.Capacity, pchUnk, (Int32) pchUnk.Capacity ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetSteamGuardNewMachineDialogResponseBB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bIsApproved, [MarshalAs(UnmanagedType.I1)] bool bIsWizardComplete );
		public void SetSteamGuardNewMachineDialogResponse( bool bIsApproved, bool bIsWizardComplete ) 
		{
			this.GetFunction<NativeSetSteamGuardNewMachineDialogResponseBB>( this.Functions.SetSteamGuardNewMachineDialogResponse165 )( this.ObjectAddress, bIsApproved, bIsWizardComplete ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetPhoneIsVerifiedB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool arg0 );
		public void SetPhoneIsVerified( bool arg0 ) 
		{
			this.GetFunction<NativeSetPhoneIsVerifiedB>( this.Functions.SetPhoneIsVerified166 )( this.ObjectAddress, arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsPhoneVerified( IntPtr thisptr );
		public bool BIsPhoneVerified(  ) 
		{
			return this.GetFunction<NativeBIsPhoneVerified>( this.Functions.BIsPhoneVerified167 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetPhoneIsIdentifyingB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool arg0 );
		public void SetPhoneIsIdentifying( bool arg0 ) 
		{
			this.GetFunction<NativeSetPhoneIsIdentifyingB>( this.Functions.SetPhoneIsIdentifying168 )( this.ObjectAddress, arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsPhoneIdentifying( IntPtr thisptr );
		public bool BIsPhoneIdentifying(  ) 
		{
			return this.GetFunction<NativeBIsPhoneIdentifying>( this.Functions.BIsPhoneIdentifying169 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetPhoneIsRequiringVerificationB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool arg0 );
		public void SetPhoneIsRequiringVerification( bool arg0 ) 
		{
			this.GetFunction<NativeSetPhoneIsRequiringVerificationB>( this.Functions.SetPhoneIsRequiringVerification170 )( this.ObjectAddress, arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsPhoneRequiringVerification( IntPtr thisptr );
		public bool BIsPhoneRequiringVerification(  ) 
		{
			return this.GetFunction<NativeBIsPhoneRequiringVerification>( this.Functions.BIsPhoneRequiringVerification171 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeChangeTwoFactorAuthOptionsI( IntPtr thisptr, Int32 eOption );
		public void ChangeTwoFactorAuthOptions( Int32 eOption ) 
		{
			this.GetFunction<NativeChangeTwoFactorAuthOptionsI>( this.Functions.ChangeTwoFactorAuthOptions172 )( this.ObjectAddress, eOption ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSet2ndFactorAuthCodeSB( IntPtr thisptr, string pchAuthCode, [MarshalAs(UnmanagedType.I1)] bool bDontRememberComputer );
		public void Set2ndFactorAuthCode( string pchAuthCode, bool bDontRememberComputer ) 
		{
			this.GetFunction<NativeSet2ndFactorAuthCodeSB>( this.Functions.Set2ndFactorAuthCode173 )( this.ObjectAddress, pchAuthCode, bDontRememberComputer ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetUserMachineNameS( IntPtr thisptr, string pchMachineName );
		public void SetUserMachineName( string pchMachineName ) 
		{
			this.GetFunction<NativeSetUserMachineNameS>( this.Functions.SetUserMachineName174 )( this.ObjectAddress, pchMachineName ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetUserMachineNameSI( IntPtr thisptr, StringBuilder pchMachineName, Int32 cbMachineName );
		public bool GetUserMachineName( StringBuilder pchMachineName ) 
		{
			return this.GetFunction<NativeGetUserMachineNameSI>( this.Functions.GetUserMachineName175 )( this.ObjectAddress, pchMachineName, (Int32) pchMachineName.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetEmailDomainFromLogonFailureSI( IntPtr thisptr, StringBuilder pchEmailDomain, Int32 cbEmailDomain );
		public bool GetEmailDomainFromLogonFailure( StringBuilder pchEmailDomain ) 
		{
			return this.GetFunction<NativeGetEmailDomainFromLogonFailureSI>( this.Functions.GetEmailDomainFromLogonFailure176 )( this.ObjectAddress, pchEmailDomain, (Int32) pchEmailDomain.Capacity ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsSubscribedAppU( IntPtr thisptr, UInt32 nAppId );
		public bool BIsSubscribedApp( UInt32 nAppId ) 
		{
			return this.GetFunction<NativeBIsSubscribedAppU>( this.Functions.BIsSubscribedApp177 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetSubscribedAppsUUB( IntPtr thisptr, ref UInt32 arg0, UInt32 arg1, [MarshalAs(UnmanagedType.I1)] bool arg2 );
		public UInt32 GetSubscribedApps( ref UInt32 arg0, UInt32 arg1, bool arg2 ) 
		{
			return this.GetFunction<NativeGetSubscribedAppsUUB>( this.Functions.GetSubscribedApps178 )( this.ObjectAddress, ref arg0, arg1, arg2 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRegisterActivationCodeS( IntPtr thisptr, string pchActivationCode );
		public UInt64 RegisterActivationCode( string pchActivationCode ) 
		{
			return this.GetFunction<NativeRegisterActivationCodeS>( this.Functions.RegisterActivationCode179 )( this.ObjectAddress, pchActivationCode ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeAckSystemIMU( IntPtr thisptr, UInt64 arg0 );
		public void AckSystemIM( UInt64 arg0 ) 
		{
			this.GetFunction<NativeAckSystemIMU>( this.Functions.AckSystemIM180 )( this.ObjectAddress, arg0 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeRequestSpecialSurveyU( IntPtr thisptr, UInt32 uSurveyId );
		public UInt64 RequestSpecialSurvey( UInt32 uSurveyId ) 
		{
			return this.GetFunction<NativeRequestSpecialSurveyU>( this.Functions.RequestSpecialSurvey181 )( this.ObjectAddress, uSurveyId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeSendSpecialSurveyResponseUBU( IntPtr thisptr, UInt32 uSurveyId, Byte[] pubData, UInt32 cubData );
		public UInt64 SendSpecialSurveyResponse( UInt32 uSurveyId, Byte[] pubData ) 
		{
			return this.GetFunction<NativeSendSpecialSurveyResponseUBU>( this.Functions.SendSpecialSurveyResponse182 )( this.ObjectAddress, uSurveyId, pubData, (UInt32) pubData.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestNotifications( IntPtr thisptr );
		public void RequestNotifications(  ) 
		{
			this.GetFunction<NativeRequestNotifications>( this.Functions.RequestNotifications183 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetAppOwnershipInfoUUUS( IntPtr thisptr, UInt32 unAppId, ref UInt32 pRTime32Created, ref UInt32 unk, StringBuilder pchCountry );
		public bool GetAppOwnershipInfo( UInt32 unAppId, ref UInt32 pRTime32Created, ref UInt32 unk, StringBuilder pchCountry ) 
		{
			return this.GetFunction<NativeGetAppOwnershipInfoUUUS>( this.Functions.GetAppOwnershipInfo184 )( this.ObjectAddress, unAppId, ref pRTime32Created, ref unk, pchCountry ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSendGameWebCallbackUS( IntPtr thisptr, UInt32 unAppId, string szData );
		public void SendGameWebCallback( UInt32 unAppId, string szData ) 
		{
			this.GetFunction<NativeSendGameWebCallbackUS>( this.Functions.SendGameWebCallback185 )( this.ObjectAddress, unAppId, szData ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeStopStreamingBI( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool arg0, Int32 arg1 );
		public void StopStreaming( bool arg0, Int32 arg1 ) 
		{
			this.GetFunction<NativeStopStreamingBI>( this.Functions.StopStreaming186 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsStreamingUIToRemoteDevice( IntPtr thisptr );
		public bool BIsStreamingUIToRemoteDevice(  ) 
		{
			return this.GetFunction<NativeBIsStreamingUIToRemoteDevice>( this.Functions.BIsStreamingUIToRemoteDevice187 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsCurrentlyNVStreaming( IntPtr thisptr );
		public bool BIsCurrentlyNVStreaming(  ) 
		{
			return this.GetFunction<NativeBIsCurrentlyNVStreaming>( this.Functions.BIsCurrentlyNVStreaming188 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestStopNVStreaming( IntPtr thisptr );
		public void RequestStopNVStreaming(  ) 
		{
			this.GetFunction<NativeRequestStopNVStreaming>( this.Functions.RequestStopNVStreaming189 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeOnBigPictureStreamingResultBB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool arg0, Byte[] arg1 );
		public void OnBigPictureStreamingResult( bool arg0, Byte[] arg1 ) 
		{
			this.GetFunction<NativeOnBigPictureStreamingResultBB>( this.Functions.OnBigPictureStreamingResult190 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeOnBigPictureStreamingDone( IntPtr thisptr );
		public void OnBigPictureStreamingDone(  ) 
		{
			this.GetFunction<NativeOnBigPictureStreamingDone>( this.Functions.OnBigPictureStreamingDone191 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeOnBigPictureStreamRestarting( IntPtr thisptr );
		public void OnBigPictureStreamRestarting(  ) 
		{
			this.GetFunction<NativeOnBigPictureStreamRestarting>( this.Functions.OnBigPictureStreamRestarting192 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLockParentalLock( IntPtr thisptr );
		public void LockParentalLock(  ) 
		{
			this.GetFunction<NativeLockParentalLock>( this.Functions.LockParentalLock193 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUnlockParentalLockS( IntPtr thisptr, string pchUnk );
		public bool UnlockParentalLock( string pchUnk ) 
		{
			return this.GetFunction<NativeUnlockParentalLockS>( this.Functions.UnlockParentalLock194 )( this.ObjectAddress, pchUnk ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsParentalLockEnabled( IntPtr thisptr );
		public bool BIsParentalLockEnabled(  ) 
		{
			return this.GetFunction<NativeBIsParentalLockEnabled>( this.Functions.BIsParentalLockEnabled195 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsParentalLockLocked( IntPtr thisptr );
		public bool BIsParentalLockLocked(  ) 
		{
			return this.GetFunction<NativeBIsParentalLockLocked>( this.Functions.BIsParentalLockLocked196 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeBlockAppU( IntPtr thisptr, UInt32 unAppID );
		public void BlockApp( UInt32 unAppID ) 
		{
			this.GetFunction<NativeBlockAppU>( this.Functions.BlockApp197 )( this.ObjectAddress, unAppID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeUnblockAppU( IntPtr thisptr, UInt32 unAppID );
		public void UnblockApp( UInt32 unAppID ) 
		{
			this.GetFunction<NativeUnblockAppU>( this.Functions.UnblockApp198 )( this.ObjectAddress, unAppID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAppBlockedU( IntPtr thisptr, UInt32 unAppID );
		public bool BIsAppBlocked( UInt32 unAppID ) 
		{
			return this.GetFunction<NativeBIsAppBlockedU>( this.Functions.BIsAppBlocked199 )( this.ObjectAddress, unAppID ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAppInBlockListU( IntPtr thisptr, UInt32 unAppID );
		public bool BIsAppInBlockList( UInt32 unAppID ) 
		{
			return this.GetFunction<NativeBIsAppInBlockListU>( this.Functions.BIsAppInBlockList200 )( this.ObjectAddress, unAppID ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeBlockFeatureE( IntPtr thisptr, EParentalFeature eParentalFeature );
		public void BlockFeature( EParentalFeature eParentalFeature ) 
		{
			this.GetFunction<NativeBlockFeatureE>( this.Functions.BlockFeature201 )( this.ObjectAddress, eParentalFeature ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeUnblockFeatureE( IntPtr thisptr, EParentalFeature eParentalFeature );
		public void UnblockFeature( EParentalFeature eParentalFeature ) 
		{
			this.GetFunction<NativeUnblockFeatureE>( this.Functions.UnblockFeature202 )( this.ObjectAddress, eParentalFeature ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsFeatureBlockedE( IntPtr thisptr, EParentalFeature eParentalFeature );
		public bool BIsFeatureBlocked( EParentalFeature eParentalFeature ) 
		{
			return this.GetFunction<NativeBIsFeatureBlockedE>( this.Functions.BIsFeatureBlocked203 )( this.ObjectAddress, eParentalFeature ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsFeatureInBlockListE( IntPtr thisptr, EParentalFeature eParentalFeature );
		public bool BIsFeatureInBlockList( EParentalFeature eParentalFeature ) 
		{
			return this.GetFunction<NativeBIsFeatureInBlockListE>( this.Functions.BIsFeatureInBlockList204 )( this.ObjectAddress, eParentalFeature ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetParentalUnlockTime( IntPtr thisptr );
		public UInt32 GetParentalUnlockTime(  ) 
		{
			return this.GetFunction<NativeGetParentalUnlockTime>( this.Functions.GetParentalUnlockTime205 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetRecoveryEmailSI( IntPtr thisptr, StringBuilder arg0, Int32 arg1 );
		public bool BGetRecoveryEmail( StringBuilder arg0, Int32 arg1 ) 
		{
			return this.GetFunction<NativeBGetRecoveryEmailSI>( this.Functions.BGetRecoveryEmail206 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRequestParentalRecoveryEmail( IntPtr thisptr );
		public void RequestParentalRecoveryEmail(  ) 
		{
			this.GetFunction<NativeRequestParentalRecoveryEmail>( this.Functions.RequestParentalRecoveryEmail207 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetSerializedParentalSettingsC( IntPtr thisptr, ref CUtlBuffer pBuffer );
		public bool BGetSerializedParentalSettings( ref CUtlBuffer pBuffer ) 
		{
			return this.GetFunction<NativeBGetSerializedParentalSettingsC>( this.Functions.BGetSerializedParentalSettings208 )( this.ObjectAddress, ref pBuffer ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBSetParentalSettingsC( IntPtr thisptr, ref CUtlBuffer pBuffer );
		public bool BSetParentalSettings( ref CUtlBuffer pBuffer ) 
		{
			return this.GetFunction<NativeBSetParentalSettingsC>( this.Functions.BSetParentalSettings209 )( this.ObjectAddress, ref pBuffer ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBDisableParentalSettings( IntPtr thisptr );
		public bool BDisableParentalSettings(  ) 
		{
			return this.GetFunction<NativeBDisableParentalSettings>( this.Functions.BDisableParentalSettings210 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetParentalWebTokenCC( IntPtr thisptr, ref CUtlBuffer arg0, ref CUtlBuffer arg1 );
		public bool BGetParentalWebToken( ref CUtlBuffer arg0, ref CUtlBuffer arg1 ) 
		{
			return this.GetFunction<NativeBGetParentalWebTokenCC>( this.Functions.BGetParentalWebToken211 )( this.ObjectAddress, ref arg0, ref arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBCanLogonOfflineMode( IntPtr thisptr );
		public bool BCanLogonOfflineMode(  ) 
		{
			return this.GetFunction<NativeBCanLogonOfflineMode>( this.Functions.BCanLogonOfflineMode212 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeLogOnOfflineMode( IntPtr thisptr );
		public EResult LogOnOfflineMode(  ) 
		{
			return this.GetFunction<NativeLogOnOfflineMode>( this.Functions.LogOnOfflineMode213 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeValidateOfflineLogonTicketS( IntPtr thisptr, string pchUnk );
		public EResult ValidateOfflineLogonTicket( string pchUnk ) 
		{
			return this.GetFunction<NativeValidateOfflineLogonTicketS>( this.Functions.ValidateOfflineLogonTicket214 )( this.ObjectAddress, pchUnk ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetOfflineLogonTicketSC( IntPtr thisptr, string pchUnk, ref COffline_OfflineLogonTicket pTicket );
		public bool BGetOfflineLogonTicket( string pchUnk, ref COffline_OfflineLogonTicket pTicket ) 
		{
			return this.GetFunction<NativeBGetOfflineLogonTicketSC>( this.Functions.BGetOfflineLogonTicket215 )( this.ObjectAddress, pchUnk, ref pTicket ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeUploadLocalClientLogs( IntPtr thisptr );
		public void UploadLocalClientLogs(  ) 
		{
			this.GetFunction<NativeUploadLocalClientLogs>( this.Functions.UploadLocalClientLogs216 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetAsyncNotificationEnabledUB( IntPtr thisptr, UInt32 arg0, [MarshalAs(UnmanagedType.I1)] bool arg1 );
		public void SetAsyncNotificationEnabled( UInt32 arg0, bool arg1 ) 
		{
			this.GetFunction<NativeSetAsyncNotificationEnabledUB>( this.Functions.SetAsyncNotificationEnabled217 )( this.ObjectAddress, arg0, arg1 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsOtherSessionPlayingU( IntPtr thisptr, ref UInt32 arg0 );
		public bool BIsOtherSessionPlaying( ref UInt32 arg0 ) 
		{
			return this.GetFunction<NativeBIsOtherSessionPlayingU>( this.Functions.BIsOtherSessionPlaying218 )( this.ObjectAddress, ref arg0 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBKickOtherPlayingSession( IntPtr thisptr );
		public bool BKickOtherPlayingSession(  ) 
		{
			return this.GetFunction<NativeBKickOtherPlayingSession>( this.Functions.BKickOtherPlayingSession219 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativePerformAccountRecoveryUpload( IntPtr thisptr );
		public void PerformAccountRecoveryUpload(  ) 
		{
			this.GetFunction<NativePerformAccountRecoveryUpload>( this.Functions.PerformAccountRecoveryUpload220 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsAccountLockedDown( IntPtr thisptr );
		public bool BIsAccountLockedDown(  ) 
		{
			return this.GetFunction<NativeBIsAccountLockedDown>( this.Functions.BIsAccountLockedDown221 )( this.ObjectAddress ); 
		}
		
	};
}
