// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class IClientRemoteStorageVTable
	{
		public IntPtr FileWrite0;
		public IntPtr GetFileSize1;
		public IntPtr FileWriteAsync2;
		public IntPtr FileReadAsync3;
		public IntPtr FileReadAsyncComplete4;
		public IntPtr FileRead5;
		public IntPtr FileForget6;
		public IntPtr FileDelete7;
		public IntPtr FileShare8;
		public IntPtr FileExists9;
		public IntPtr FilePersisted10;
		public IntPtr GetFileTimestamp11;
		public IntPtr SetSyncPlatforms12;
		public IntPtr GetSyncPlatforms13;
		public IntPtr FileWriteStreamOpen14;
		public IntPtr FileWriteStreamClose15;
		public IntPtr FileWriteStreamCancel16;
		public IntPtr FileWriteStreamWriteChunk17;
		public IntPtr GetFileCount18;
		public IntPtr GetFileNameAndSize19;
		public IntPtr GetQuota20;
		public IntPtr IsCloudEnabledForAccount21;
		public IntPtr IsCloudEnabledForApp22;
		public IntPtr SetCloudEnabledForApp23;
		public IntPtr UGCDownload24;
		public IntPtr UGCDownloadToLocation25;
		public IntPtr GetUGCDownloadProgress26;
		public IntPtr GetUGCDetails27;
		public IntPtr UGCRead28;
		public IntPtr GetCachedUGCCount29;
		public IntPtr GetCachedUGCHandle30;
		public IntPtr PublishFile31;
		public IntPtr PublishVideo32;
		public IntPtr PublishVideoFromURL33;
		public IntPtr CreatePublishedFileUpdateRequest34;
		public IntPtr UpdatePublishedFileFile35;
		public IntPtr UpdatePublishedFilePreviewFile36;
		public IntPtr UpdatePublishedFileTitle37;
		public IntPtr UpdatePublishedFileDescription38;
		public IntPtr UpdatePublishedFileSetChangeDescription39;
		public IntPtr UpdatePublishedFileVisibility40;
		public IntPtr UpdatePublishedFileTags41;
		public IntPtr UpdatePublishedFileURL42;
		public IntPtr CommitPublishedFileUpdate43;
		public IntPtr GetPublishedFileDetails44;
		public IntPtr DeletePublishedFile45;
		public IntPtr EnumerateUserPublishedFiles46;
		public IntPtr SubscribePublishedFile47;
		public IntPtr EnumerateUserSubscribedFiles48;
		public IntPtr UnsubscribePublishedFile49;
		public IntPtr SetUserPublishedFileAction50;
		public IntPtr EnumeratePublishedFilesByUserAction51;
		public IntPtr EnumerateUserSubscribedFilesWithUpdates52;
		public IntPtr GetCREItemVoteSummary53;
		public IntPtr UpdateUserPublishedItemVote54;
		public IntPtr GetUserPublishedItemVoteDetails55;
		public IntPtr EnumerateUserSharedWorkshopFiles56;
		public IntPtr EnumeratePublishedWorkshopFiles57;
		public IntPtr EGetFileSyncState58;
		public IntPtr BIsFileSyncing59;
		public IntPtr FilePersist60;
		public IntPtr FileFetch61;
		public IntPtr ResolvePath62;
		public IntPtr FileTouch63;
		public IntPtr SetCloudEnabledForAccount64;
		public IntPtr LoadLocalFileInfoCache65;
		public IntPtr EvaluateRemoteStorageSyncState66;
		public IntPtr GetRemoteStorageSyncState67;
		public IntPtr HaveLatestFilesLocally68;
		public IntPtr GetConflictingFileTimestamps69;
		public IntPtr ResolveSyncConflict70;
		public IntPtr SynchronizeApp71;
		public IntPtr IsAppSyncInProgress72;
		public IntPtr RunAutoCloudOnAppLaunch73;
		public IntPtr RunAutoCloudOnAppExit74;
		public IntPtr ResetFileRequestState75;
		public IntPtr ClearPublishFileUpdateRequests76;
		public IntPtr GetSubscribedFileDownloadCount77;
		public IntPtr BGetSubscribedFileDownloadInfo78;
		public IntPtr BGetSubscribedFileDownloadInfo79;
		public IntPtr PauseSubscribedFileDownloadsForApp80;
		public IntPtr ResumeSubscribedFileDownloadsForApp81;
		public IntPtr PauseAllSubscribedFileDownloads82;
		public IntPtr ResumeAllSubscribedFileDownloads83;
		private IntPtr DTorIClientRemoteStorage84;
	};
	
	[InteropHelp.InterfaceVersion("CLIENTREMOTESTORAGE_INTERFACE_VERSION001")]
	public class IClientRemoteStorage : InteropHelp.NativeWrapper<IClientRemoteStorageVTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeFileWriteUESBI( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, Byte[] pvData, Int32 cubData );
		public EResult FileWrite( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, Byte[] pvData ) 
		{
			return this.GetFunction<NativeFileWriteUESBI>( this.Functions.FileWrite0 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile, pvData, (Int32) pvData.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetFileSizeUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public Int32 GetFileSize( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeGetFileSizeUES>( this.Functions.GetFileSize1 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeFileWriteAsyncUESC( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string arg2, ref CUtlBuffer arg3 );
		public UInt64 FileWriteAsync( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string arg2, ref CUtlBuffer arg3 ) 
		{
			return this.GetFunction<NativeFileWriteAsyncUESC>( this.Functions.FileWriteAsync2 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, arg2, ref arg3 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeFileReadAsyncUESUU( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string arg2, UInt32 arg3, UInt32 arg4 );
		public UInt64 FileReadAsync( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string arg2, UInt32 arg3, UInt32 arg4 ) 
		{
			return this.GetFunction<NativeFileReadAsyncUESUU>( this.Functions.FileReadAsync3 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, arg2, arg3, arg4 ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileReadAsyncCompleteUUBU( IntPtr thisptr, UInt32 nAppId, UInt64 arg1, Byte[] arg2, UInt32 arg3 );
		public bool FileReadAsyncComplete( UInt32 nAppId, UInt64 arg1, Byte[] arg2, UInt32 arg3 ) 
		{
			return this.GetFunction<NativeFileReadAsyncCompleteUUBU>( this.Functions.FileReadAsyncComplete4 )( this.ObjectAddress, nAppId, arg1, arg2, arg3 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeFileReadUESBI( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, Byte[] pvData, Int32 cubDataToRead );
		public Int32 FileRead( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, Byte[] pvData ) 
		{
			return this.GetFunction<NativeFileReadUESBI>( this.Functions.FileRead5 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile, pvData, (Int32) pvData.Length ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileForgetUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public bool FileForget( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFileForgetUES>( this.Functions.FileForget6 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileDeleteUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public bool FileDelete( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFileDeleteUES>( this.Functions.FileDelete7 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeFileShareUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public UInt64 FileShare( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFileShareUES>( this.Functions.FileShare8 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileExistsUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public bool FileExists( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFileExistsUES>( this.Functions.FileExists9 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFilePersistedUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public bool FilePersisted( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFilePersistedUES>( this.Functions.FilePersisted10 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int64 NativeGetFileTimestampUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public Int64 GetFileTimestamp( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeGetFileTimestampUES>( this.Functions.GetFileTimestamp11 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetSyncPlatformsUESE( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, ERemoteStoragePlatform eRemoteStoragePlatform );
		public bool SetSyncPlatforms( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, ERemoteStoragePlatform eRemoteStoragePlatform ) 
		{
			return this.GetFunction<NativeSetSyncPlatformsUESE>( this.Functions.SetSyncPlatforms12 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile, eRemoteStoragePlatform ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate ERemoteStoragePlatform NativeGetSyncPlatformsUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public ERemoteStoragePlatform GetSyncPlatforms( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeGetSyncPlatformsUES>( this.Functions.GetSyncPlatforms13 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeFileWriteStreamOpenUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public UInt64 FileWriteStreamOpen( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFileWriteStreamOpenUES>( this.Functions.FileWriteStreamOpen14 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeFileWriteStreamCloseU( IntPtr thisptr, UInt64 hStream );
		public EResult FileWriteStreamClose( UInt64 hStream ) 
		{
			return this.GetFunction<NativeFileWriteStreamCloseU>( this.Functions.FileWriteStreamClose15 )( this.ObjectAddress, hStream ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeFileWriteStreamCancelU( IntPtr thisptr, UInt64 hStream );
		public EResult FileWriteStreamCancel( UInt64 hStream ) 
		{
			return this.GetFunction<NativeFileWriteStreamCancelU>( this.Functions.FileWriteStreamCancel16 )( this.ObjectAddress, hStream ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeFileWriteStreamWriteChunkUBI( IntPtr thisptr, UInt64 hStream, Byte[] pvData, Int32 cubData );
		public EResult FileWriteStreamWriteChunk( UInt64 hStream, Byte[] pvData ) 
		{
			return this.GetFunction<NativeFileWriteStreamWriteChunkUBI>( this.Functions.FileWriteStreamWriteChunk17 )( this.ObjectAddress, hStream, pvData, (Int32) pvData.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetFileCountUB( IntPtr thisptr, UInt32 nAppId, [MarshalAs(UnmanagedType.I1)] bool bFromExternalAPI );
		public Int32 GetFileCount( UInt32 nAppId, bool bFromExternalAPI ) 
		{
			return this.GetFunction<NativeGetFileCountUB>( this.Functions.GetFileCount18 )( this.ObjectAddress, nAppId, bFromExternalAPI ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate IntPtr NativeGetFileNameAndSizeUIEIB( IntPtr thisptr, UInt32 nAppId, Int32 iFile, ref ERemoteStorageFileRoot peRemoteStorageFileRoot, ref Int32 pnFileSizeInBytes, [MarshalAs(UnmanagedType.I1)] bool bFromExternalAPI );
		public string GetFileNameAndSize( UInt32 nAppId, Int32 iFile, ref ERemoteStorageFileRoot peRemoteStorageFileRoot, ref Int32 pnFileSizeInBytes, bool bFromExternalAPI ) 
		{
			return InteropHelp.DecodeANSIReturn( Marshal.PtrToStringAnsi( this.GetFunction<NativeGetFileNameAndSizeUIEIB>( this.Functions.GetFileNameAndSize19 )( this.ObjectAddress, nAppId, iFile, ref peRemoteStorageFileRoot, ref pnFileSizeInBytes, bFromExternalAPI ) ) ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQuotaUII( IntPtr thisptr, UInt32 nAppId, ref Int32 pnTotalBytes, ref Int32 pnAvailableBytes );
		public bool GetQuota( UInt32 nAppId, ref Int32 pnTotalBytes, ref Int32 pnAvailableBytes ) 
		{
			return this.GetFunction<NativeGetQuotaUII>( this.Functions.GetQuota20 )( this.ObjectAddress, nAppId, ref pnTotalBytes, ref pnAvailableBytes ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsCloudEnabledForAccount( IntPtr thisptr );
		public bool IsCloudEnabledForAccount(  ) 
		{
			return this.GetFunction<NativeIsCloudEnabledForAccount>( this.Functions.IsCloudEnabledForAccount21 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsCloudEnabledForAppU( IntPtr thisptr, UInt32 nAppId );
		public bool IsCloudEnabledForApp( UInt32 nAppId ) 
		{
			return this.GetFunction<NativeIsCloudEnabledForAppU>( this.Functions.IsCloudEnabledForApp22 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetCloudEnabledForAppUB( IntPtr thisptr, UInt32 nAppId, [MarshalAs(UnmanagedType.I1)] bool bEnable );
		public void SetCloudEnabledForApp( UInt32 nAppId, bool bEnable ) 
		{
			this.GetFunction<NativeSetCloudEnabledForAppUB>( this.Functions.SetCloudEnabledForApp23 )( this.ObjectAddress, nAppId, bEnable ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeUGCDownloadUBU( IntPtr thisptr, UInt64 hContent, [MarshalAs(UnmanagedType.I1)] bool bUseNewCallback, UInt32 uUnk );
		public UInt64 UGCDownload( UInt64 hContent, bool bUseNewCallback, UInt32 uUnk ) 
		{
			return this.GetFunction<NativeUGCDownloadUBU>( this.Functions.UGCDownload24 )( this.ObjectAddress, hContent, bUseNewCallback, uUnk ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeUGCDownloadToLocationUSU( IntPtr thisptr, UInt64 hContent, string cszLocation, UInt32 uUnk );
		public UInt64 UGCDownloadToLocation( UInt64 hContent, string cszLocation, UInt32 uUnk ) 
		{
			return this.GetFunction<NativeUGCDownloadToLocationUSU>( this.Functions.UGCDownloadToLocation25 )( this.ObjectAddress, hContent, cszLocation, uUnk ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetUGCDownloadProgressUUU( IntPtr thisptr, UInt64 hContent, ref UInt32 puDownloadedBytes, ref UInt32 puTotalBytes );
		public bool GetUGCDownloadProgress( UInt64 hContent, ref UInt32 puDownloadedBytes, ref UInt32 puTotalBytes ) 
		{
			return this.GetFunction<NativeGetUGCDownloadProgressUUU>( this.Functions.GetUGCDownloadProgress26 )( this.ObjectAddress, hContent, ref puDownloadedBytes, ref puTotalBytes ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetUGCDetailsUUSIC( IntPtr thisptr, UInt64 hContent, ref UInt32 pnAppID, StringBuilder ppchName, ref Int32 pnFileSizeInBytes, ref UInt64 pSteamIDOwner );
		public bool GetUGCDetails( UInt64 hContent, ref UInt32 pnAppID, StringBuilder ppchName, ref Int32 pnFileSizeInBytes, ref CSteamID pSteamIDOwner ) 
		{
			UInt64 s0 = 0; var result = this.GetFunction<NativeGetUGCDetailsUUSIC>( this.Functions.GetUGCDetails27 )( this.ObjectAddress, hContent, ref pnAppID, ppchName, ref pnFileSizeInBytes, ref s0 ); pSteamIDOwner = new CSteamID(s0); return result;
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeUGCReadUBIUE( IntPtr thisptr, UInt64 hContent, Byte[] pvData, Int32 cubDataToRead, UInt32 uOffset, EUGCReadAction eAction );
		public Int32 UGCRead( UInt64 hContent, Byte[] pvData, UInt32 uOffset, EUGCReadAction eAction ) 
		{
			return this.GetFunction<NativeUGCReadUBIUE>( this.Functions.UGCRead28 )( this.ObjectAddress, hContent, pvData, (Int32) pvData.Length, uOffset, eAction ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCachedUGCCount( IntPtr thisptr );
		public Int32 GetCachedUGCCount(  ) 
		{
			return this.GetFunction<NativeGetCachedUGCCount>( this.Functions.GetCachedUGCCount29 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeGetCachedUGCHandleI( IntPtr thisptr, Int32 iCachedContent );
		public UInt64 GetCachedUGCHandle( Int32 iCachedContent ) 
		{
			return this.GetFunction<NativeGetCachedUGCHandleI>( this.Functions.GetCachedUGCHandle30 )( this.ObjectAddress, iCachedContent ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativePublishFileUESSUSSESE( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string cszFileName, string cszPreviewFileName, UInt32 nConsumerAppId, string cszTitle, string cszDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags, EWorkshopFileType eType );
		public UInt64 PublishFile( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string cszFileName, string cszPreviewFileName, UInt32 nConsumerAppId, string cszTitle, string cszDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags, EWorkshopFileType eType ) 
		{
			return this.GetFunction<NativePublishFileUESSUSSESE>( this.Functions.PublishFile31 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, cszFileName, cszPreviewFileName, nConsumerAppId, cszTitle, cszDescription, eVisibility, ref pTags, eType ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativePublishVideoUESSESUSSES( IntPtr thisptr, UInt32 nAppId, EWorkshopVideoProvider eVideoProvider, string cszVideoAccountName, string cszVideoIdentifier, ERemoteStorageFileRoot eRemoteStorageFileRoot, string cszFileName, UInt32 nConsumerAppId, string cszTitle, string cszDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags );
		public UInt64 PublishVideo( UInt32 nAppId, EWorkshopVideoProvider eVideoProvider, string cszVideoAccountName, string cszVideoIdentifier, ERemoteStorageFileRoot eRemoteStorageFileRoot, string cszFileName, UInt32 nConsumerAppId, string cszTitle, string cszDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags ) 
		{
			return this.GetFunction<NativePublishVideoUESSESUSSES>( this.Functions.PublishVideo32 )( this.ObjectAddress, nAppId, eVideoProvider, cszVideoAccountName, cszVideoIdentifier, eRemoteStorageFileRoot, cszFileName, nConsumerAppId, cszTitle, cszDescription, eVisibility, ref pTags ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativePublishVideoFromURLUESSUSSES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string cszVideoURL, string cszFileName, UInt32 nConsumerAppId, string cszTitle, string cszDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags );
		public UInt64 PublishVideoFromURL( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string cszVideoURL, string cszFileName, UInt32 nConsumerAppId, string cszTitle, string cszDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags ) 
		{
			return this.GetFunction<NativePublishVideoFromURLUESSUSSES>( this.Functions.PublishVideoFromURL33 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, cszVideoURL, cszFileName, nConsumerAppId, cszTitle, cszDescription, eVisibility, ref pTags ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeCreatePublishedFileUpdateRequestUU( IntPtr thisptr, UInt32 nAppId, UInt64 unPublishedFileId );
		public UInt64 CreatePublishedFileUpdateRequest( UInt32 nAppId, UInt64 unPublishedFileId ) 
		{
			return this.GetFunction<NativeCreatePublishedFileUpdateRequestUU>( this.Functions.CreatePublishedFileUpdateRequest34 )( this.ObjectAddress, nAppId, unPublishedFileId ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFileFileUS( IntPtr thisptr, UInt64 hUpdateRequest, string cszFile );
		public bool UpdatePublishedFileFile( UInt64 hUpdateRequest, string cszFile ) 
		{
			return this.GetFunction<NativeUpdatePublishedFileFileUS>( this.Functions.UpdatePublishedFileFile35 )( this.ObjectAddress, hUpdateRequest, cszFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFilePreviewFileUS( IntPtr thisptr, UInt64 hUpdateRequest, string cszPreviewFile );
		public bool UpdatePublishedFilePreviewFile( UInt64 hUpdateRequest, string cszPreviewFile ) 
		{
			return this.GetFunction<NativeUpdatePublishedFilePreviewFileUS>( this.Functions.UpdatePublishedFilePreviewFile36 )( this.ObjectAddress, hUpdateRequest, cszPreviewFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFileTitleUS( IntPtr thisptr, UInt64 hUpdateRequest, string cszTitle );
		public bool UpdatePublishedFileTitle( UInt64 hUpdateRequest, string cszTitle ) 
		{
			return this.GetFunction<NativeUpdatePublishedFileTitleUS>( this.Functions.UpdatePublishedFileTitle37 )( this.ObjectAddress, hUpdateRequest, cszTitle ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFileDescriptionUS( IntPtr thisptr, UInt64 hUpdateRequest, string cszDescription );
		public bool UpdatePublishedFileDescription( UInt64 hUpdateRequest, string cszDescription ) 
		{
			return this.GetFunction<NativeUpdatePublishedFileDescriptionUS>( this.Functions.UpdatePublishedFileDescription38 )( this.ObjectAddress, hUpdateRequest, cszDescription ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFileSetChangeDescriptionUS( IntPtr thisptr, UInt64 hUpdateRequest, string cszDescription );
		public bool UpdatePublishedFileSetChangeDescription( UInt64 hUpdateRequest, string cszDescription ) 
		{
			return this.GetFunction<NativeUpdatePublishedFileSetChangeDescriptionUS>( this.Functions.UpdatePublishedFileSetChangeDescription39 )( this.ObjectAddress, hUpdateRequest, cszDescription ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFileVisibilityUE( IntPtr thisptr, UInt64 hUpdateRequest, ERemoteStoragePublishedFileVisibility eVisibility );
		public bool UpdatePublishedFileVisibility( UInt64 hUpdateRequest, ERemoteStoragePublishedFileVisibility eVisibility ) 
		{
			return this.GetFunction<NativeUpdatePublishedFileVisibilityUE>( this.Functions.UpdatePublishedFileVisibility40 )( this.ObjectAddress, hUpdateRequest, eVisibility ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFileTagsUS( IntPtr thisptr, UInt64 hUpdateRequest, ref SteamParamStringArray_t pTags );
		public bool UpdatePublishedFileTags( UInt64 hUpdateRequest, ref SteamParamStringArray_t pTags ) 
		{
			return this.GetFunction<NativeUpdatePublishedFileTagsUS>( this.Functions.UpdatePublishedFileTags41 )( this.ObjectAddress, hUpdateRequest, ref pTags ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeUpdatePublishedFileURLUS( IntPtr thisptr, UInt64 hUpdateRequest, string cszURL );
		public bool UpdatePublishedFileURL( UInt64 hUpdateRequest, string cszURL ) 
		{
			return this.GetFunction<NativeUpdatePublishedFileURLUS>( this.Functions.UpdatePublishedFileURL42 )( this.ObjectAddress, hUpdateRequest, cszURL ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeCommitPublishedFileUpdateUEU( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, UInt64 hUpdateRequest );
		public UInt64 CommitPublishedFileUpdate( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, UInt64 hUpdateRequest ) 
		{
			return this.GetFunction<NativeCommitPublishedFileUpdateUEU>( this.Functions.CommitPublishedFileUpdate43 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, hUpdateRequest ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeGetPublishedFileDetailsUBU( IntPtr thisptr, UInt64 unPublishedFileId, [MarshalAs(UnmanagedType.I1)] bool bUseNewCallback, UInt32 arg2 );
		public UInt64 GetPublishedFileDetails( UInt64 unPublishedFileId, bool bUseNewCallback, UInt32 arg2 ) 
		{
			return this.GetFunction<NativeGetPublishedFileDetailsUBU>( this.Functions.GetPublishedFileDetails44 )( this.ObjectAddress, unPublishedFileId, bUseNewCallback, arg2 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeDeletePublishedFileU( IntPtr thisptr, UInt64 unPublishedFileId );
		public UInt64 DeletePublishedFile( UInt64 unPublishedFileId ) 
		{
			return this.GetFunction<NativeDeletePublishedFileU>( this.Functions.DeletePublishedFile45 )( this.ObjectAddress, unPublishedFileId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeEnumerateUserPublishedFilesUUE( IntPtr thisptr, UInt32 nAppId, UInt32 uStartIndex, ERemoteStoragePublishedFileSortOrder eOrder );
		public UInt64 EnumerateUserPublishedFiles( UInt32 nAppId, UInt32 uStartIndex, ERemoteStoragePublishedFileSortOrder eOrder ) 
		{
			return this.GetFunction<NativeEnumerateUserPublishedFilesUUE>( this.Functions.EnumerateUserPublishedFiles46 )( this.ObjectAddress, nAppId, uStartIndex, eOrder ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeSubscribePublishedFileUU( IntPtr thisptr, UInt32 nAppId, UInt64 unPublishedFileId );
		public UInt64 SubscribePublishedFile( UInt32 nAppId, UInt64 unPublishedFileId ) 
		{
			return this.GetFunction<NativeSubscribePublishedFileUU>( this.Functions.SubscribePublishedFile47 )( this.ObjectAddress, nAppId, unPublishedFileId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeEnumerateUserSubscribedFilesUUBE( IntPtr thisptr, UInt32 nAppId, UInt32 uStartIndex, Byte uListType, EPublishedFileInfoMatchingFileType eMatchingFileType );
		public UInt64 EnumerateUserSubscribedFiles( UInt32 nAppId, UInt32 uStartIndex, Byte uListType, EPublishedFileInfoMatchingFileType eMatchingFileType ) 
		{
			return this.GetFunction<NativeEnumerateUserSubscribedFilesUUBE>( this.Functions.EnumerateUserSubscribedFiles48 )( this.ObjectAddress, nAppId, uStartIndex, uListType, eMatchingFileType ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeUnsubscribePublishedFileUU( IntPtr thisptr, UInt32 nAppId, UInt64 unPublishedFileId );
		public UInt64 UnsubscribePublishedFile( UInt32 nAppId, UInt64 unPublishedFileId ) 
		{
			return this.GetFunction<NativeUnsubscribePublishedFileUU>( this.Functions.UnsubscribePublishedFile49 )( this.ObjectAddress, nAppId, unPublishedFileId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeSetUserPublishedFileActionUUE( IntPtr thisptr, UInt32 nAppId, UInt64 unPublishedFileId, EWorkshopFileAction eAction );
		public UInt64 SetUserPublishedFileAction( UInt32 nAppId, UInt64 unPublishedFileId, EWorkshopFileAction eAction ) 
		{
			return this.GetFunction<NativeSetUserPublishedFileActionUUE>( this.Functions.SetUserPublishedFileAction50 )( this.ObjectAddress, nAppId, unPublishedFileId, eAction ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeEnumeratePublishedFilesByUserActionUEU( IntPtr thisptr, UInt32 nAppId, EWorkshopFileAction eAction, UInt32 uStartIndex );
		public UInt64 EnumeratePublishedFilesByUserAction( UInt32 nAppId, EWorkshopFileAction eAction, UInt32 uStartIndex ) 
		{
			return this.GetFunction<NativeEnumeratePublishedFilesByUserActionUEU>( this.Functions.EnumeratePublishedFilesByUserAction51 )( this.ObjectAddress, nAppId, eAction, uStartIndex ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeEnumerateUserSubscribedFilesWithUpdatesUUU( IntPtr thisptr, UInt32 nAppId, UInt32 uStartIndex, UInt32 uStartTime );
		public UInt64 EnumerateUserSubscribedFilesWithUpdates( UInt32 nAppId, UInt32 uStartIndex, UInt32 uStartTime ) 
		{
			return this.GetFunction<NativeEnumerateUserSubscribedFilesWithUpdatesUUU>( this.Functions.EnumerateUserSubscribedFilesWithUpdates52 )( this.ObjectAddress, nAppId, uStartIndex, uStartTime ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeGetCREItemVoteSummaryU( IntPtr thisptr, UInt64 unPublishedFileId );
		public UInt64 GetCREItemVoteSummary( UInt64 unPublishedFileId ) 
		{
			return this.GetFunction<NativeGetCREItemVoteSummaryU>( this.Functions.GetCREItemVoteSummary53 )( this.ObjectAddress, unPublishedFileId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeUpdateUserPublishedItemVoteUB( IntPtr thisptr, UInt64 unPublishedFileId, [MarshalAs(UnmanagedType.I1)] bool bVoteUp );
		public UInt64 UpdateUserPublishedItemVote( UInt64 unPublishedFileId, bool bVoteUp ) 
		{
			return this.GetFunction<NativeUpdateUserPublishedItemVoteUB>( this.Functions.UpdateUserPublishedItemVote54 )( this.ObjectAddress, unPublishedFileId, bVoteUp ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeGetUserPublishedItemVoteDetailsU( IntPtr thisptr, UInt64 unPublishedFileId );
		public UInt64 GetUserPublishedItemVoteDetails( UInt64 unPublishedFileId ) 
		{
			return this.GetFunction<NativeGetUserPublishedItemVoteDetailsU>( this.Functions.GetUserPublishedItemVoteDetails55 )( this.ObjectAddress, unPublishedFileId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeEnumerateUserSharedWorkshopFilesUCUSS( IntPtr thisptr, UInt32 nAppId, UInt64 creatorSteamID, UInt32 uStartIndex, ref SteamParamStringArray_t pRequiredTags, ref SteamParamStringArray_t pExcludedTags );
		public UInt64 EnumerateUserSharedWorkshopFiles( UInt32 nAppId, CSteamID creatorSteamID, UInt32 uStartIndex, ref SteamParamStringArray_t pRequiredTags, ref SteamParamStringArray_t pExcludedTags ) 
		{
			return this.GetFunction<NativeEnumerateUserSharedWorkshopFilesUCUSS>( this.Functions.EnumerateUserSharedWorkshopFiles56 )( this.ObjectAddress, nAppId, creatorSteamID.ConvertToUint64(), uStartIndex, ref pRequiredTags, ref pExcludedTags ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeEnumeratePublishedWorkshopFilesUEEUUUSS( IntPtr thisptr, UInt32 nAppId, EWorkshopEnumerationType eType, EPublishedFileInfoMatchingFileType eFileType, UInt32 uStartIndex, UInt32 cDays, UInt32 cCount, ref SteamParamStringArray_t pTags, ref SteamParamStringArray_t pUserTags );
		public UInt64 EnumeratePublishedWorkshopFiles( UInt32 nAppId, EWorkshopEnumerationType eType, EPublishedFileInfoMatchingFileType eFileType, UInt32 uStartIndex, UInt32 cDays, UInt32 cCount, ref SteamParamStringArray_t pTags, ref SteamParamStringArray_t pUserTags ) 
		{
			return this.GetFunction<NativeEnumeratePublishedWorkshopFilesUEEUUUSS>( this.Functions.EnumeratePublishedWorkshopFiles57 )( this.ObjectAddress, nAppId, eType, eFileType, uStartIndex, cDays, cCount, ref pTags, ref pUserTags ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EFileRemoteStorageSyncState NativeEGetFileSyncStateUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public EFileRemoteStorageSyncState EGetFileSyncState( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeEGetFileSyncStateUES>( this.Functions.EGetFileSyncState58 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBIsFileSyncingUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public bool BIsFileSyncing( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeBIsFileSyncingUES>( this.Functions.BIsFileSyncing59 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeFilePersistUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public EResult FilePersist( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFilePersistUES>( this.Functions.FilePersist60 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileFetchUES( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile );
		public bool FileFetch( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile ) 
		{
			return this.GetFunction<NativeFileFetchUES>( this.Functions.FileFetch61 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeResolvePathUESSU( IntPtr thisptr, UInt32 nAppID, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchRelPath, StringBuilder pchDest, UInt32 cchDest );
		public bool ResolvePath( UInt32 nAppID, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchRelPath, StringBuilder pchDest ) 
		{
			return this.GetFunction<NativeResolvePathUESSU>( this.Functions.ResolvePath62 )( this.ObjectAddress, nAppID, eRemoteStorageFileRoot, pchRelPath, pchDest, (UInt32) pchDest.Capacity ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate EResult NativeFileTouchUESB( IntPtr thisptr, UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, [MarshalAs(UnmanagedType.I1)] bool arg3 );
		public EResult FileTouch( UInt32 nAppId, ERemoteStorageFileRoot eRemoteStorageFileRoot, string pchFile, bool arg3 ) 
		{
			return this.GetFunction<NativeFileTouchUESB>( this.Functions.FileTouch63 )( this.ObjectAddress, nAppId, eRemoteStorageFileRoot, pchFile, arg3 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetCloudEnabledForAccountB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bEnabled );
		public void SetCloudEnabledForAccount( bool bEnabled ) 
		{
			this.GetFunction<NativeSetCloudEnabledForAccountB>( this.Functions.SetCloudEnabledForAccount64 )( this.ObjectAddress, bEnabled ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLoadLocalFileInfoCacheU( IntPtr thisptr, UInt32 nAppId );
		public void LoadLocalFileInfoCache( UInt32 nAppId ) 
		{
			this.GetFunction<NativeLoadLocalFileInfoCacheU>( this.Functions.LoadLocalFileInfoCache65 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeEvaluateRemoteStorageSyncStateUB( IntPtr thisptr, UInt32 nAppId, [MarshalAs(UnmanagedType.I1)] bool bUnk );
		public void EvaluateRemoteStorageSyncState( UInt32 nAppId, bool bUnk ) 
		{
			this.GetFunction<NativeEvaluateRemoteStorageSyncStateUB>( this.Functions.EvaluateRemoteStorageSyncState66 )( this.ObjectAddress, nAppId, bUnk ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate ERemoteStorageSyncState NativeGetRemoteStorageSyncStateU( IntPtr thisptr, UInt32 nAppId );
		public ERemoteStorageSyncState GetRemoteStorageSyncState( UInt32 nAppId ) 
		{
			return this.GetFunction<NativeGetRemoteStorageSyncStateU>( this.Functions.GetRemoteStorageSyncState67 )( this.ObjectAddress, nAppId ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeHaveLatestFilesLocallyU( IntPtr thisptr, UInt32 nAppId );
		public bool HaveLatestFilesLocally( UInt32 nAppId ) 
		{
			return this.GetFunction<NativeHaveLatestFilesLocallyU>( this.Functions.HaveLatestFilesLocally68 )( this.ObjectAddress, nAppId ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetConflictingFileTimestampsUUU( IntPtr thisptr, UInt32 nAppId, ref UInt32 pnTimestampLocal, ref UInt32 pnTimestampRemote );
		public bool GetConflictingFileTimestamps( UInt32 nAppId, ref UInt32 pnTimestampLocal, ref UInt32 pnTimestampRemote ) 
		{
			return this.GetFunction<NativeGetConflictingFileTimestampsUUU>( this.Functions.GetConflictingFileTimestamps69 )( this.ObjectAddress, nAppId, ref pnTimestampLocal, ref pnTimestampRemote ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeResolveSyncConflictUB( IntPtr thisptr, UInt32 nAppId, [MarshalAs(UnmanagedType.I1)] bool bAcceptLocalFiles );
		public bool ResolveSyncConflict( UInt32 nAppId, bool bAcceptLocalFiles ) 
		{
			return this.GetFunction<NativeResolveSyncConflictUB>( this.Functions.ResolveSyncConflict70 )( this.ObjectAddress, nAppId, bAcceptLocalFiles ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSynchronizeAppUBB( IntPtr thisptr, UInt32 nAppId, [MarshalAs(UnmanagedType.I1)] bool bSyncClient, [MarshalAs(UnmanagedType.I1)] bool bSyncServer );
		public bool SynchronizeApp( UInt32 nAppId, bool bSyncClient, bool bSyncServer ) 
		{
			return this.GetFunction<NativeSynchronizeAppUBB>( this.Functions.SynchronizeApp71 )( this.ObjectAddress, nAppId, bSyncClient, bSyncServer ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsAppSyncInProgressU( IntPtr thisptr, UInt32 nAppId );
		public bool IsAppSyncInProgress( UInt32 nAppId ) 
		{
			return this.GetFunction<NativeIsAppSyncInProgressU>( this.Functions.IsAppSyncInProgress72 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRunAutoCloudOnAppLaunchU( IntPtr thisptr, UInt32 nAppId );
		public void RunAutoCloudOnAppLaunch( UInt32 nAppId ) 
		{
			this.GetFunction<NativeRunAutoCloudOnAppLaunchU>( this.Functions.RunAutoCloudOnAppLaunch73 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeRunAutoCloudOnAppExitU( IntPtr thisptr, UInt32 nAppId );
		public void RunAutoCloudOnAppExit( UInt32 nAppId ) 
		{
			this.GetFunction<NativeRunAutoCloudOnAppExitU>( this.Functions.RunAutoCloudOnAppExit74 )( this.ObjectAddress, nAppId ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeResetFileRequestStateU( IntPtr thisptr, UInt32 nAppId );
		public bool ResetFileRequestState( UInt32 nAppId ) 
		{
			return this.GetFunction<NativeResetFileRequestStateU>( this.Functions.ResetFileRequestState75 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeClearPublishFileUpdateRequestsU( IntPtr thisptr, UInt32 nAppId );
		public void ClearPublishFileUpdateRequests( UInt32 nAppId ) 
		{
			this.GetFunction<NativeClearPublishFileUpdateRequestsU>( this.Functions.ClearPublishFileUpdateRequests76 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetSubscribedFileDownloadCount( IntPtr thisptr );
		public Int32 GetSubscribedFileDownloadCount(  ) 
		{
			return this.GetFunction<NativeGetSubscribedFileDownloadCount>( this.Functions.GetSubscribedFileDownloadCount77 )( this.ObjectAddress ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetSubscribedFileDownloadInfoIUUUU( IntPtr thisptr, Int32 iFile, ref UInt64 punPublishedFileId, ref UInt32 puBytesDownloaded, ref UInt32 puBytesExpected, ref UInt32 pnAppId );
		public bool BGetSubscribedFileDownloadInfo( Int32 iFile, ref UInt64 punPublishedFileId, ref UInt32 puBytesDownloaded, ref UInt32 puBytesExpected, ref UInt32 pnAppId ) 
		{
			return this.GetFunction<NativeBGetSubscribedFileDownloadInfoIUUUU>( this.Functions.BGetSubscribedFileDownloadInfo78 )( this.ObjectAddress, iFile, ref punPublishedFileId, ref puBytesDownloaded, ref puBytesExpected, ref pnAppId ); 
		}
		
		[return: MarshalAs(UnmanagedType.I1)]
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeBGetSubscribedFileDownloadInfoUUUU( IntPtr thisptr, UInt64 unPublishedFileId, ref UInt32 puBytesDownloaded, ref UInt32 puBytesExpected, ref UInt32 pnAppId );
		public bool BGetSubscribedFileDownloadInfo( UInt64 unPublishedFileId, ref UInt32 puBytesDownloaded, ref UInt32 puBytesExpected, ref UInt32 pnAppId ) 
		{
			return this.GetFunction<NativeBGetSubscribedFileDownloadInfoUUUU>( this.Functions.BGetSubscribedFileDownloadInfo79 )( this.ObjectAddress, unPublishedFileId, ref puBytesDownloaded, ref puBytesExpected, ref pnAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativePauseSubscribedFileDownloadsForAppU( IntPtr thisptr, UInt32 nAppId );
		public void PauseSubscribedFileDownloadsForApp( UInt32 nAppId ) 
		{
			this.GetFunction<NativePauseSubscribedFileDownloadsForAppU>( this.Functions.PauseSubscribedFileDownloadsForApp80 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeResumeSubscribedFileDownloadsForAppU( IntPtr thisptr, UInt32 nAppId );
		public void ResumeSubscribedFileDownloadsForApp( UInt32 nAppId ) 
		{
			this.GetFunction<NativeResumeSubscribedFileDownloadsForAppU>( this.Functions.ResumeSubscribedFileDownloadsForApp81 )( this.ObjectAddress, nAppId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativePauseAllSubscribedFileDownloads( IntPtr thisptr );
		public void PauseAllSubscribedFileDownloads(  ) 
		{
			this.GetFunction<NativePauseAllSubscribedFileDownloads>( this.Functions.PauseAllSubscribedFileDownloads82 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeResumeAllSubscribedFileDownloads( IntPtr thisptr );
		public void ResumeAllSubscribedFileDownloads(  ) 
		{
			this.GetFunction<NativeResumeAllSubscribedFileDownloads>( this.Functions.ResumeAllSubscribedFileDownloads83 )( this.ObjectAddress ); 
		}
		
	};
}
